export const SHOP_DRAWING_IFC_PRECAST_SECTIONS = [
  {
    id: "sec-sdp-1",
    name: "Drawing Submission Details",
    order: 0,
    description: "Drawing identification and submission tracking",
    allowRepeats: false,
    items: [
      { id: "sdp-1", name: "Drawing Number", type: "text_field", required: true, placeholder: "e.g. SD-PC-001" },
      { id: "sdp-2", name: "Drawing Title", type: "text_field", required: true, placeholder: "Drawing title as shown on title block" },
      { id: "sdp-3", name: "Revision Number", type: "text_field", required: true, placeholder: "e.g. Rev A, Rev 01" },
      { id: "sdp-4", name: "Submission Date", type: "datetime_field", required: true },
      { id: "sdp-5", name: "Prepared By (Detailer / Draftsperson)", type: "text_field", required: true, placeholder: "Name of person who prepared the drawing" },
      { id: "sdp-6", name: "Subcontractor / Fabricator", type: "text_field", required: true, placeholder: "Precast manufacturer name" },
      { id: "sdp-7", name: "Panel Mark / Element Reference", type: "text_field", required: true, placeholder: "e.g. W01, C05, SP-L3-01" },
      { id: "sdp-8", name: "Submission Type", type: "dropdown", required: true, options: ["Initial Submission", "Re-Submission", "Final IFC Issue", "Revision to IFC"] },
    ],
  },
  {
    id: "sec-sdp-2",
    name: "Title Block & General Compliance",
    order: 1,
    description: "Verify title block information and general drawing compliance",
    allowRepeats: false,
    items: [
      { id: "sdp-10", name: "Project name, number, and address correct", type: "pass_fail_flag", required: true, description: "Title block matches contract documents" },
      { id: "sdp-11", name: "Drawing number and revision match register", type: "pass_fail_flag", required: true, description: "Drawing number matches the document register and transmittal" },
      { id: "sdp-12", name: "Scale clearly noted and appropriate", type: "pass_fail_flag", required: true, description: "Plan and section scales are correct (e.g. 1:20, 1:50)" },
      { id: "sdp-13", name: "North point shown on plans", type: "pass_fail_flag", required: true, description: "Orientation reference provided on plan views" },
      { id: "sdp-14", name: "Grid lines match architectural/structural grids", type: "pass_fail_flag", required: true, description: "Grid references align with the coordinated model/drawings" },
      { id: "sdp-15", name: "Revision history / cloud markings shown", type: "pass_fail_flag", required: true, description: "Changes from previous revision are clearly identified" },
      { id: "sdp-16", name: "CAD / BIM file reference noted", type: "yes_no_na", required: false, description: "Source model or file reference included" },
    ],
  },
  {
    id: "sec-sdp-3",
    name: "Geometry & Dimensions",
    order: 2,
    description: "Verify panel geometry, dimensions, and tolerances",
    allowRepeats: false,
    items: [
      { id: "sdp-20", name: "Overall panel dimensions correct (L x W x D)", type: "pass_fail_flag", required: true, description: "Length, width, and thickness match design intent" },
      { id: "sdp-21", name: "Panel thickness matches structural design", type: "pass_fail_flag", required: true, description: "Structural thickness, cover to reo, and sandwich panel layers verified" },
      { id: "sdp-22", name: "Opening locations and sizes correct", type: "pass_fail_flag", required: true, description: "Windows, doors, penetrations match architectural drawings" },
      { id: "sdp-23", name: "Joint widths and locations dimensioned", type: "pass_fail_flag", required: true, description: "Panel-to-panel and panel-to-slab joints shown and dimensioned" },
      { id: "sdp-24", name: "Setout dimensions from grid/datum verified", type: "pass_fail_flag", required: true, description: "Panel position relative to structural grids and RL datums" },
      { id: "sdp-25", name: "Chamfers, rebates, and edge profiles shown", type: "pass_fail_flag", required: true, description: "Edge treatments and joint profiles dimensioned" },
      { id: "sdp-26", name: "Tolerances noted per AS 3610 / AS 3850", type: "yes_no_na", required: true, description: "Manufacturing and erection tolerances referenced" },
      { id: "sdp-27", name: "Levels (RLs) and floor-to-floor heights correct", type: "pass_fail_flag", required: true, description: "Reduced levels match structural and architectural documentation" },
    ],
  },
  {
    id: "sec-sdp-4",
    name: "Reinforcement & Structural Details",
    order: 3,
    description: "Verify reinforcement detailing and structural connections",
    allowRepeats: false,
    items: [
      { id: "sdp-30", name: "Reinforcement schedule complete and legible", type: "pass_fail_flag", required: true, description: "Bar marks, sizes, spacings, and lengths clearly shown" },
      { id: "sdp-31", name: "Cover to reinforcement noted", type: "pass_fail_flag", required: true, description: "Concrete cover complies with AS 3600 for exposure class" },
      { id: "sdp-32", name: "Lapping and splicing details shown", type: "pass_fail_flag", required: true, description: "Lap lengths and splice locations per structural engineer" },
      { id: "sdp-33", name: "Lifting anchor type, capacity, and positions shown", type: "pass_fail_flag", required: true, description: "Lifting inserts suit panel weight and stripping/erection loads" },
      { id: "sdp-34", name: "Bracing connection details shown", type: "pass_fail_flag", required: true, description: "Temporary bracing inserts and connection details for erection" },
      { id: "sdp-35", name: "Permanent connection details shown", type: "pass_fail_flag", required: true, description: "Corbels, dowels, ferrules, brackets for permanent fixing" },
      { id: "sdp-36", name: "Concrete strength and mix specified", type: "pass_fail_flag", required: true, description: "f'c grade and any special mix requirements noted" },
      { id: "sdp-37", name: "Mesh / ligatures at openings detailed", type: "pass_fail_flag", required: true, description: "Trimmer bars and additional reinforcement around openings" },
      { id: "sdp-38", name: "Structural engineer approval stamp / comment status", type: "dropdown", required: true, options: ["Approved", "Approved with Comments", "Revise and Resubmit", "Not Yet Submitted", "Rejected"] },
    ],
  },
  {
    id: "sec-sdp-5",
    name: "Cast-In Items & Embedments",
    order: 4,
    description: "Verify all cast-in items, services, and embedments",
    allowRepeats: false,
    items: [
      { id: "sdp-40", name: "Electrical conduits and boxes shown", type: "yes_no_na", required: true, description: "Conduit runs, outlet boxes, and switchboard locations" },
      { id: "sdp-41", name: "Plumbing penetrations and sleeves shown", type: "yes_no_na", required: true, description: "Pipe penetrations, puddle flanges, and fire collar locations" },
      { id: "sdp-42", name: "Mechanical penetrations shown", type: "yes_no_na", required: true, description: "HVAC, exhaust, and mechanical service penetrations" },
      { id: "sdp-43", name: "Fire-rated cast-in items noted", type: "yes_no_na", required: true, description: "Fire collars, intumescent wraps, and rated service crossings" },
      { id: "sdp-44", name: "Facade fixing inserts / ferrules shown", type: "yes_no_na", required: true, description: "Cladding, louvre, and screen fixing embedments" },
      { id: "sdp-45", name: "Waterproofing details at penetrations", type: "yes_no_na", required: true, description: "Waterproof membranes, upturns, and sealant details" },
      { id: "sdp-46", name: "Services coordination sign-off obtained", type: "pass_fail_flag", required: true, description: "All services trades have reviewed and approved cast-in locations" },
    ],
  },
  {
    id: "sec-sdp-6",
    name: "Finishes & Architectural Requirements",
    order: 5,
    description: "Verify finish specifications and architectural compliance",
    allowRepeats: false,
    items: [
      { id: "sdp-50", name: "Surface finish type specified", type: "pass_fail_flag", required: true, description: "Off-form, honed, polished, exposed aggregate, painted, etc." },
      { id: "sdp-51", name: "Finish sample / colour reference noted", type: "yes_no_na", required: true, description: "Reference to approved sample panel or colour chart" },
      { id: "sdp-52", name: "Reveal / feature line locations correct", type: "yes_no_na", required: true, description: "Architectural reveals and feature lines match facade drawings" },
      { id: "sdp-53", name: "Drip groove / weathering details shown", type: "yes_no_na", required: true, description: "Drip moulds at sill and head details to prevent water staining" },
      { id: "sdp-54", name: "External face clearly identified", type: "pass_fail_flag", required: true, description: "A-face and B-face clearly marked on the drawing" },
    ],
  },
  {
    id: "sec-sdp-7",
    name: "Coordination & Cross-Discipline Check",
    order: 6,
    description: "Cross-discipline coordination and clash checking",
    allowRepeats: false,
    items: [
      { id: "sdp-60", name: "Checked against latest architectural drawings", type: "pass_fail_flag", required: true, description: "Verified against current revision of architectural plans/elevations" },
      { id: "sdp-61", name: "Checked against latest structural drawings", type: "pass_fail_flag", required: true, description: "Verified against current revision of structural plans/details" },
      { id: "sdp-62", name: "Checked against coordinated services model", type: "yes_no_na", required: true, description: "BIM coordination model or services drawings reviewed for clashes" },
      { id: "sdp-63", name: "RFIs or design queries resolved", type: "pass_fail_flag", required: true, description: "All outstanding RFIs relevant to this panel have been closed out" },
      { id: "sdp-64", name: "Adjacent panel interfaces checked", type: "pass_fail_flag", required: true, description: "Panel-to-panel connections, joints, and step alignments verified" },
      { id: "sdp-65", name: "Erection sequence considered", type: "yes_no_na", required: true, description: "Drawing accounts for practical erection sequence and crane access" },
    ],
  },
  {
    id: "sec-sdp-8",
    name: "Review Outcome & Sign-Off",
    order: 7,
    description: "Final review outcome and authorisation",
    allowRepeats: false,
    items: [
      { id: "sdp-70", name: "Review Outcome", type: "dropdown", required: true, options: ["Approved - Issue for Construction", "Approved with Comments - Resubmit", "Not Approved - Revise & Resubmit", "For Information Only"] },
      { id: "sdp-71", name: "Review Comments", type: "textarea", required: false, placeholder: "Detail any comments, markups, or required changes" },
      { id: "sdp-72", name: "Reviewer Name", type: "text_field", required: true, placeholder: "Name of person conducting the review" },
      { id: "sdp-73", name: "Reviewer Signature", type: "signature_field", required: true },
      { id: "sdp-74", name: "Review Date", type: "datetime_field", required: true },
      { id: "sdp-75", name: "Design Manager / PM Endorsement", type: "signature_field", required: false, description: "Second-level sign-off if required by project procedures" },
    ],
  },
];

export const SHOP_DRAWING_JOINERY_SECTIONS = [
  {
    id: "sec-sdj-1",
    name: "Drawing Submission Details",
    order: 0,
    description: "Joinery shop drawing identification and submission tracking",
    allowRepeats: false,
    items: [
      { id: "sdj-1", name: "Drawing Number", type: "text_field", required: true, placeholder: "e.g. SD-JN-001" },
      { id: "sdj-2", name: "Drawing Title", type: "text_field", required: true, placeholder: "Drawing title as shown on title block" },
      { id: "sdj-3", name: "Revision Number", type: "text_field", required: true, placeholder: "e.g. Rev A, Rev 01" },
      { id: "sdj-4", name: "Submission Date", type: "datetime_field", required: true },
      { id: "sdj-5", name: "Prepared By", type: "text_field", required: true, placeholder: "Joinery manufacturer / draftsperson" },
      { id: "sdj-6", name: "Joinery Subcontractor", type: "text_field", required: true, placeholder: "Joinery manufacturer / supplier name" },
      { id: "sdj-7", name: "Location / Room Reference", type: "text_field", required: true, placeholder: "e.g. Level 3 Kitchen, L05 Reception Desk" },
      { id: "sdj-8", name: "Submission Type", type: "dropdown", required: true, options: ["Initial Submission", "Re-Submission", "Final IFC Issue", "Revision to IFC"] },
    ],
  },
  {
    id: "sec-sdj-2",
    name: "Title Block & General Compliance",
    order: 1,
    description: "Verify title block and drawing presentation standards",
    allowRepeats: false,
    items: [
      { id: "sdj-10", name: "Project name, number, and address correct", type: "pass_fail_flag", required: true },
      { id: "sdj-11", name: "Drawing number and revision match register", type: "pass_fail_flag", required: true },
      { id: "sdj-12", name: "Scale clearly noted and appropriate", type: "pass_fail_flag", required: true, description: "Plans at 1:50, details at 1:5 or 1:2 as appropriate" },
      { id: "sdj-13", name: "Room / area reference keyed to architectural plans", type: "pass_fail_flag", required: true },
      { id: "sdj-14", name: "Revision cloud markings or change log included", type: "pass_fail_flag", required: true },
    ],
  },
  {
    id: "sec-sdj-3",
    name: "Dimensions & Geometry",
    order: 2,
    description: "Verify joinery dimensions, clearances, and spatial coordination",
    allowRepeats: false,
    items: [
      { id: "sdj-20", name: "Overall dimensions correct (W x D x H)", type: "pass_fail_flag", required: true, description: "Width, depth, and height match design intent and room layout" },
      { id: "sdj-21", name: "Bench / counter heights match specification", type: "pass_fail_flag", required: true, description: "Standard 900mm bench, 720mm desk, or as specified" },
      { id: "sdj-22", name: "Wall-to-wall and floor-to-ceiling clearances checked", type: "pass_fail_flag", required: true, description: "Site dimensions verified with tolerances for installation" },
      { id: "sdj-23", name: "Door and drawer sizes correct", type: "pass_fail_flag", required: true, description: "Opening sizes, overlay/inset dimensions, and hardware clearances" },
      { id: "sdj-24", name: "Setout from walls / datum points dimensioned", type: "pass_fail_flag", required: true },
      { id: "sdj-25", name: "Plumbing rough-in locations coordinated", type: "yes_no_na", required: true, description: "Sink waste, water supply, and dishwasher connections positioned correctly" },
      { id: "sdj-26", name: "Electrical rough-in locations coordinated", type: "yes_no_na", required: true, description: "Power points, data outlets, and appliance connections positioned" },
    ],
  },
  {
    id: "sec-sdj-4",
    name: "Materials & Finishes",
    order: 3,
    description: "Verify material selections, finishes, and hardware",
    allowRepeats: false,
    items: [
      { id: "sdj-30", name: "Board / substrate type specified", type: "pass_fail_flag", required: true, description: "MR MDF, plywood, particleboard, or solid timber as required" },
      { id: "sdj-31", name: "Laminate / veneer / paint finish specified", type: "pass_fail_flag", required: true, description: "Colour code, brand, and product reference provided" },
      { id: "sdj-32", name: "Finish matches approved sample / schedule", type: "pass_fail_flag", required: true, description: "Finish aligns with architect's finishes schedule and approved samples" },
      { id: "sdj-33", name: "Benchtop material and edge profile specified", type: "pass_fail_flag", required: true, description: "Stone, solid surface, laminate - brand, colour, and edge detail" },
      { id: "sdj-34", name: "Hardware schedule included", type: "pass_fail_flag", required: true, description: "Handles, hinges, runners, soft-close, locks - brand and product codes" },
      { id: "sdj-35", name: "Grain direction and veneer matching noted", type: "yes_no_na", required: true, description: "Timber veneer grain direction and book-matching requirements" },
      { id: "sdj-36", name: "Moisture resistance grade suitable for location", type: "pass_fail_flag", required: true, description: "MR board for wet areas, HMR for high-moisture zones" },
    ],
  },
  {
    id: "sec-sdj-5",
    name: "Services & Accessory Coordination",
    order: 4,
    description: "Coordination with mechanical, electrical, and plumbing services",
    allowRepeats: false,
    items: [
      { id: "sdj-40", name: "Sink / basin cut-out dimensions correct", type: "yes_no_na", required: true, description: "Undermount/overmount sink template and cutout verified" },
      { id: "sdj-41", name: "Tap / mixer locations marked", type: "yes_no_na", required: true, description: "Hole positions for tapware match manufacturer specs" },
      { id: "sdj-42", name: "Appliance recesses correct", type: "yes_no_na", required: true, description: "Oven, microwave, fridge, dishwasher spaces match appliance dimensions" },
      { id: "sdj-43", name: "Ventilation / extraction provisions shown", type: "yes_no_na", required: true, description: "Rangehood ducting, air gaps behind fridges, etc." },
      { id: "sdj-44", name: "Access panels for services shown", type: "yes_no_na", required: true, description: "Access to valves, cleanouts, and junction boxes" },
      { id: "sdj-45", name: "Lighting provisions coordinated", type: "yes_no_na", required: true, description: "Under-cabinet lighting, LED strips, task lighting wiring" },
    ],
  },
  {
    id: "sec-sdj-6",
    name: "Compliance & Standards",
    order: 5,
    description: "Regulatory and accessibility compliance checks",
    allowRepeats: false,
    items: [
      { id: "sdj-50", name: "Accessibility (AS 1428) requirements met", type: "yes_no_na", required: true, description: "Accessible benchtop heights, clearances, and reach ranges where required" },
      { id: "sdj-51", name: "Fire rating / smoke compartmentation maintained", type: "yes_no_na", required: true, description: "Joinery does not breach fire-rated walls or bulkheads" },
      { id: "sdj-52", name: "Formaldehyde emission rating noted (E0/E1)", type: "pass_fail_flag", required: true, description: "Board products comply with specified emission class" },
      { id: "sdj-53", name: "NCC / BCA compliance for wet area materials", type: "yes_no_na", required: true, description: "Appropriate materials for bathrooms, kitchens, laundries" },
    ],
  },
  {
    id: "sec-sdj-7",
    name: "Coordination & Cross-Discipline Check",
    order: 6,
    description: "Cross-discipline coordination verification",
    allowRepeats: false,
    items: [
      { id: "sdj-60", name: "Checked against latest architectural drawings", type: "pass_fail_flag", required: true },
      { id: "sdj-61", name: "Checked against latest interior design drawings", type: "pass_fail_flag", required: true },
      { id: "sdj-62", name: "Checked against finishes schedule", type: "pass_fail_flag", required: true },
      { id: "sdj-63", name: "Checked against hydraulic / electrical layouts", type: "pass_fail_flag", required: true },
      { id: "sdj-64", name: "RFIs or design queries resolved", type: "pass_fail_flag", required: true },
      { id: "sdj-65", name: "Site measurements verified (if applicable)", type: "yes_no_na", required: true, description: "Physical site dimensions confirmed before final manufacture" },
    ],
  },
  {
    id: "sec-sdj-8",
    name: "Review Outcome & Sign-Off",
    order: 7,
    description: "Final review outcome and authorisation",
    allowRepeats: false,
    items: [
      { id: "sdj-70", name: "Review Outcome", type: "dropdown", required: true, options: ["Approved - Issue for Construction", "Approved with Comments - Resubmit", "Not Approved - Revise & Resubmit", "For Information Only"] },
      { id: "sdj-71", name: "Review Comments", type: "textarea", required: false, placeholder: "Detail any comments, markups, or required changes" },
      { id: "sdj-72", name: "Reviewer Name", type: "text_field", required: true },
      { id: "sdj-73", name: "Reviewer Signature", type: "signature_field", required: true },
      { id: "sdj-74", name: "Review Date", type: "datetime_field", required: true },
      { id: "sdj-75", name: "Design Manager Endorsement", type: "signature_field", required: false },
    ],
  },
];

export const SHOP_DRAWING_STAIRS_SECTIONS = [
  {
    id: "sec-sds-1",
    name: "Drawing Submission Details",
    order: 0,
    description: "Stair shop drawing identification and submission tracking",
    allowRepeats: false,
    items: [
      { id: "sds-1", name: "Drawing Number", type: "text_field", required: true, placeholder: "e.g. SD-ST-001" },
      { id: "sds-2", name: "Drawing Title", type: "text_field", required: true, placeholder: "Drawing title as shown on title block" },
      { id: "sds-3", name: "Revision Number", type: "text_field", required: true, placeholder: "e.g. Rev A, Rev 01" },
      { id: "sds-4", name: "Submission Date", type: "datetime_field", required: true },
      { id: "sds-5", name: "Prepared By", type: "text_field", required: true, placeholder: "Stair manufacturer / draftsperson" },
      { id: "sds-6", name: "Stair Subcontractor / Fabricator", type: "text_field", required: true, placeholder: "Stair manufacturer / steelwork fabricator" },
      { id: "sds-7", name: "Stair Reference / Location", type: "text_field", required: true, placeholder: "e.g. Stair 01, Fire Stair A, L3-L4" },
      { id: "sds-8", name: "Stair Type", type: "dropdown", required: true, options: ["Precast Concrete", "Steel - Painted", "Steel - Galvanised", "Steel - Stainless", "Timber", "Composite / Mixed"] },
      { id: "sds-9", name: "Submission Type", type: "dropdown", required: true, options: ["Initial Submission", "Re-Submission", "Final IFC Issue", "Revision to IFC"] },
    ],
  },
  {
    id: "sec-sds-2",
    name: "Title Block & General Compliance",
    order: 1,
    description: "Verify title block and drawing presentation",
    allowRepeats: false,
    items: [
      { id: "sds-10", name: "Project name, number, and address correct", type: "pass_fail_flag", required: true },
      { id: "sds-11", name: "Drawing number and revision match register", type: "pass_fail_flag", required: true },
      { id: "sds-12", name: "Scale clearly noted and appropriate", type: "pass_fail_flag", required: true },
      { id: "sds-13", name: "Grid lines / level references match structural drawings", type: "pass_fail_flag", required: true },
      { id: "sds-14", name: "Revision history / change log included", type: "pass_fail_flag", required: true },
    ],
  },
  {
    id: "sec-sds-3",
    name: "Geometry & BCA Compliance",
    order: 2,
    description: "Verify stair geometry meets NCC/BCA requirements and design intent",
    allowRepeats: false,
    items: [
      { id: "sds-20", name: "Going (tread depth) compliant - min 250mm", type: "pass_fail_flag", required: true, description: "NCC Vol 1 Part D1.1 / AS 1657 minimum going requirement" },
      { id: "sds-21", name: "Riser height compliant - max 190mm", type: "pass_fail_flag", required: true, description: "NCC Vol 1 Part D1.1 maximum riser height" },
      { id: "sds-22", name: "2R + G formula within 550-700mm range", type: "pass_fail_flag", required: true, description: "Riser/going ratio compliance (typically 600-620mm preferred)" },
      { id: "sds-23", name: "All risers uniform height (max 5mm variation)", type: "pass_fail_flag", required: true, description: "Uniform riser heights throughout each flight" },
      { id: "sds-24", name: "Stair width compliant", type: "pass_fail_flag", required: true, description: "Clear width between handrails meets NCC requirement (min 1000mm, fire stairs min per D1.6)" },
      { id: "sds-25", name: "Landing dimensions correct", type: "pass_fail_flag", required: true, description: "Landing length min equals stair width, mid-landings for flights >18 risers" },
      { id: "sds-26", name: "Headroom clearance min 2000mm", type: "pass_fail_flag", required: true, description: "Clear headroom measured vertically from nosing line to soffit" },
      { id: "sds-27", name: "Nosing profile / strip shown", type: "pass_fail_flag", required: true, description: "Anti-slip nosing strips or tread profile per AS 1428.1" },
      { id: "sds-28", name: "Floor-to-floor height verified against structure", type: "pass_fail_flag", required: true, description: "Total rise matches structural floor levels exactly" },
      { id: "sds-29", name: "Number of risers per flight correct", type: "pass_fail_flag", required: true, description: "Flight length and riser count matches geometry" },
    ],
  },
  {
    id: "sec-sds-4",
    name: "Balustrade & Handrail Details",
    order: 3,
    description: "Verify balustrade and handrail compliance with NCC and AS 1170.1",
    allowRepeats: false,
    items: [
      { id: "sds-30", name: "Handrail height 865-1000mm from nosing", type: "pass_fail_flag", required: true, description: "NCC D2.16 handrail height requirement" },
      { id: "sds-31", name: "Handrail profile graspable (circular 30-65mm dia)", type: "pass_fail_flag", required: true, description: "Handrail diameter and profile per AS 1428.1 / NCC" },
      { id: "sds-32", name: "Handrail extends 300mm past top and bottom nosing", type: "pass_fail_flag", required: true, description: "Horizontal extension at landings per NCC / AS 1428.1" },
      { id: "sds-33", name: "Handrail continuous along full length", type: "pass_fail_flag", required: true, description: "No gaps or breaks in handrail along flights and landings" },
      { id: "sds-34", name: "Balustrade height min 1000mm (865mm on stair)", type: "pass_fail_flag", required: true, description: "Guard height per NCC D2.16" },
      { id: "sds-35", name: "Balustrade infill - no climbable elements", type: "pass_fail_flag", required: true, description: "No horizontal rails or climbable features within the guard" },
      { id: "sds-36", name: "Baluster spacing max 125mm", type: "pass_fail_flag", required: true, description: "Maximum gap between balusters or infill openings" },
      { id: "sds-37", name: "Balustrade structural loading capacity noted", type: "pass_fail_flag", required: true, description: "Designed for minimum horizontal load per AS 1170.1" },
      { id: "sds-38", name: "Balustrade material and finish specified", type: "pass_fail_flag", required: true, description: "Steel, glass, aluminium - finish type and colour" },
    ],
  },
  {
    id: "sec-sds-5",
    name: "Structural & Connection Details",
    order: 4,
    description: "Verify structural connections, fixings, and support details",
    allowRepeats: false,
    items: [
      { id: "sds-40", name: "Stringer / carriage connection to structure shown", type: "pass_fail_flag", required: true, description: "Top and bottom landing connections to slab/beam detailed" },
      { id: "sds-41", name: "Base plate / anchor bolt details shown", type: "pass_fail_flag", required: true, description: "Fixing details including bolt sizes, embedment, and edge distances" },
      { id: "sds-42", name: "Welding details and specifications noted", type: "yes_no_na", required: true, description: "Weld types, sizes, and AS/NZS 1554 category" },
      { id: "sds-43", name: "Steel member sizes and grades specified", type: "pass_fail_flag", required: true, description: "Section sizes (PFC, UB, RHS, etc.) and steel grade (AS/NZS 3678/3679)" },
      { id: "sds-44", name: "Surface treatment / coating specified", type: "pass_fail_flag", required: true, description: "Galvanising, paint system, intumescent coating, or powder coat" },
      { id: "sds-45", name: "Deflection and vibration criteria addressed", type: "yes_no_na", required: true, description: "Design for serviceability and vibration comfort" },
      { id: "sds-46", name: "Structural engineer review status", type: "dropdown", required: true, options: ["Approved", "Approved with Comments", "Revise and Resubmit", "Not Yet Submitted", "Rejected"] },
    ],
  },
  {
    id: "sec-sds-6",
    name: "Fire & Accessibility Compliance",
    order: 5,
    description: "Fire stair and accessibility requirements",
    allowRepeats: false,
    items: [
      { id: "sds-50", name: "Fire rating of stair enclosure maintained", type: "yes_no_na", required: true, description: "Stair passes through fire-rated shaft - penetrations sealed" },
      { id: "sds-51", name: "Fire-rated door thresholds / landings coordinated", type: "yes_no_na", required: true, description: "Landing levels align with fire door sills" },
      { id: "sds-52", name: "Intumescent coating specified (if steel in fire stair)", type: "yes_no_na", required: true, description: "Fire protection coating for exposed steel in fire stairs" },
      { id: "sds-53", name: "Tactile ground surface indicators (TGSIs) shown", type: "yes_no_na", required: true, description: "Warning TGSIs at top and bottom landings per AS 1428.4.1" },
      { id: "sds-54", name: "Luminous egress path markings noted", type: "yes_no_na", required: true, description: "Photoluminescent strips on nosings and handrails for high-rise per AS 1680 / NCC" },
      { id: "sds-55", name: "Stair pressurisation provisions coordinated", type: "yes_no_na", required: true, description: "Coordination with mechanical for stair pressurisation system" },
    ],
  },
  {
    id: "sec-sds-7",
    name: "Coordination & Cross-Discipline Check",
    order: 6,
    description: "Cross-discipline coordination verification",
    allowRepeats: false,
    items: [
      { id: "sds-60", name: "Checked against latest architectural drawings", type: "pass_fail_flag", required: true },
      { id: "sds-61", name: "Checked against latest structural drawings", type: "pass_fail_flag", required: true },
      { id: "sds-62", name: "Checked against coordinated services model", type: "yes_no_na", required: true, description: "No clashes with services running through stair void" },
      { id: "sds-63", name: "RFIs or design queries resolved", type: "pass_fail_flag", required: true },
      { id: "sds-64", name: "Site measurements verified (if retrofit)", type: "yes_no_na", required: true },
    ],
  },
  {
    id: "sec-sds-8",
    name: "Review Outcome & Sign-Off",
    order: 7,
    description: "Final review outcome and authorisation",
    allowRepeats: false,
    items: [
      { id: "sds-70", name: "Review Outcome", type: "dropdown", required: true, options: ["Approved - Issue for Construction", "Approved with Comments - Resubmit", "Not Approved - Revise & Resubmit", "For Information Only"] },
      { id: "sds-71", name: "Review Comments", type: "textarea", required: false, placeholder: "Detail any comments, markups, or required changes" },
      { id: "sds-72", name: "Reviewer Name", type: "text_field", required: true },
      { id: "sds-73", name: "Reviewer Signature", type: "signature_field", required: true },
      { id: "sds-74", name: "Review Date", type: "datetime_field", required: true },
      { id: "sds-75", name: "Design Manager Endorsement", type: "signature_field", required: false },
    ],
  },
];

export const IFC_ARCHITECTURAL_SECTIONS = [
  {
    id: "sec-ifc-1",
    name: "Drawing Issue Details",
    order: 0,
    description: "IFC issue identification and tracking",
    allowRepeats: false,
    items: [
      { id: "ifc-1", name: "Drawing Number", type: "text_field", required: true, placeholder: "e.g. A-100, A-201" },
      { id: "ifc-2", name: "Drawing Title", type: "text_field", required: true, placeholder: "Drawing title as shown on title block" },
      { id: "ifc-3", name: "Revision Number", type: "text_field", required: true, placeholder: "e.g. Rev P01, Rev C01" },
      { id: "ifc-4", name: "Issue Date", type: "datetime_field", required: true },
      { id: "ifc-5", name: "Prepared By (Architect / Draftsperson)", type: "text_field", required: true },
      { id: "ifc-6", name: "Architectural Practice", type: "text_field", required: true, placeholder: "Architectural firm name" },
      { id: "ifc-7", name: "Discipline", type: "dropdown", required: true, options: ["Architecture - General Arrangement", "Architecture - Detailed", "Interior Design", "Landscape Architecture"] },
      { id: "ifc-8", name: "Drawing Type", type: "dropdown", required: true, options: ["Site Plan", "Floor Plan", "Reflected Ceiling Plan", "Elevations", "Sections", "Details", "Schedules", "Specifications", "3D Views / Perspectives"] },
      { id: "ifc-9", name: "Issue Purpose", type: "dropdown", required: true, options: ["Issued for Construction", "Issued for Construction - Amended", "Issued for Tender", "Issued for Review", "Issued for Coordination", "Preliminary", "For Information"] },
    ],
  },
  {
    id: "sec-ifc-2",
    name: "Title Block & Drawing Standards",
    order: 1,
    description: "Verify title block completeness and drawing standards compliance",
    allowRepeats: false,
    items: [
      { id: "ifc-10", name: "Project name, number, and address correct", type: "pass_fail_flag", required: true },
      { id: "ifc-11", name: "Client / developer name correct", type: "pass_fail_flag", required: true },
      { id: "ifc-12", name: "Drawing number follows agreed numbering convention", type: "pass_fail_flag", required: true, description: "Matches drawing register numbering system" },
      { id: "ifc-13", name: "Revision correctly incremented from previous issue", type: "pass_fail_flag", required: true },
      { id: "ifc-14", name: "Status / purpose stamp matches issue type", type: "pass_fail_flag", required: true, description: "IFC stamp, watermark, or status block correctly shown" },
      { id: "ifc-15", name: "Scale correctly noted and bar scale shown", type: "pass_fail_flag", required: true },
      { id: "ifc-16", name: "North point on all plans", type: "pass_fail_flag", required: true },
      { id: "ifc-17", name: "Grid lines and datums match coordinated set", type: "pass_fail_flag", required: true },
      { id: "ifc-18", name: "Legend / abbreviations table complete", type: "pass_fail_flag", required: true },
      { id: "ifc-19", name: "Revision history table up to date", type: "pass_fail_flag", required: true },
    ],
  },
  {
    id: "sec-ifc-3",
    name: "Design Coordination Check",
    order: 2,
    description: "Cross-discipline coordination and consistency verification",
    allowRepeats: false,
    items: [
      { id: "ifc-20", name: "Coordinated with current structural drawings", type: "pass_fail_flag", required: true, description: "Column locations, beam depths, slab edges, and setdowns match" },
      { id: "ifc-21", name: "Coordinated with current hydraulic drawings", type: "pass_fail_flag", required: true, description: "Wet area falls, floor wastes, risers, and pipe routes" },
      { id: "ifc-22", name: "Coordinated with current mechanical drawings", type: "pass_fail_flag", required: true, description: "Ceiling bulkheads, plant rooms, duct routes, and diffuser locations" },
      { id: "ifc-23", name: "Coordinated with current electrical drawings", type: "pass_fail_flag", required: true, description: "Switch locations, GPO positions, lighting layouts" },
      { id: "ifc-24", name: "Coordinated with current fire engineering drawings", type: "pass_fail_flag", required: true, description: "Fire compartments, hydrant locations, sprinkler heads, smoke detectors" },
      { id: "ifc-25", name: "Coordinated with landscape / external works drawings", type: "yes_no_na", required: true },
      { id: "ifc-26", name: "BIM model up to date and federated", type: "yes_no_na", required: true, description: "Revit model current and all disciplines federated for clash detection" },
      { id: "ifc-27", name: "All clash detection issues resolved", type: "pass_fail_flag", required: true, description: "No outstanding clashes from coordination meetings" },
      { id: "ifc-28", name: "RFIs / design queries resolved before issue", type: "pass_fail_flag", required: true, description: "All outstanding RFIs and design queries closed out" },
    ],
  },
  {
    id: "sec-ifc-4",
    name: "NCC / BCA Compliance",
    order: 3,
    description: "National Construction Code and Building Code of Australia compliance",
    allowRepeats: false,
    items: [
      { id: "ifc-30", name: "Building classification correct per NCC Vol 1", type: "pass_fail_flag", required: true, description: "Building class (1-10) correctly identified and applied" },
      { id: "ifc-31", name: "Fire compartmentation shown correctly", type: "pass_fail_flag", required: true, description: "Fire walls, smoke walls, and floor separations per NCC Spec C1.1" },
      { id: "ifc-32", name: "Fire-rated construction noted on drawings", type: "pass_fail_flag", required: true, description: "FRL notation (structural adequacy / integrity / insulation)" },
      { id: "ifc-33", name: "Exit travel distances compliant", type: "pass_fail_flag", required: true, description: "Max travel distance to exits per NCC D1.4" },
      { id: "ifc-34", name: "Exit widths adequate", type: "pass_fail_flag", required: true, description: "Exit door and corridor widths per NCC D1.6" },
      { id: "ifc-35", name: "Accessible paths of travel shown", type: "pass_fail_flag", required: true, description: "Accessible routes per AS 1428.1 from entrance to all required areas" },
      { id: "ifc-36", name: "Accessible sanitary facilities provided", type: "yes_no_na", required: true, description: "Accessible toilets, ambulant toilets per NCC F2.4" },
      { id: "ifc-37", name: "Stair and ramp compliance verified", type: "pass_fail_flag", required: true, description: "Stair geometry, ramp gradients, handrails per NCC Part D1" },
      { id: "ifc-38", name: "Natural light and ventilation compliance", type: "pass_fail_flag", required: true, description: "Window areas and openable areas per NCC F4 / F6" },
      { id: "ifc-39", name: "Energy efficiency (Section J) provisions shown", type: "yes_no_na", required: true, description: "Glazing performance, insulation, and thermal breaks noted" },
    ],
  },
  {
    id: "sec-ifc-5",
    name: "Dimensions & Setout",
    order: 4,
    description: "Verify completeness and accuracy of dimensions",
    allowRepeats: false,
    items: [
      { id: "ifc-40", name: "All rooms dimensioned (length x width)", type: "pass_fail_flag", required: true },
      { id: "ifc-41", name: "All openings dimensioned (doors, windows)", type: "pass_fail_flag", required: true, description: "Width, height, and head height from FFL" },
      { id: "ifc-42", name: "Setout dimensions from grids provided", type: "pass_fail_flag", required: true, description: "Key walls and elements dimensioned from structural grids" },
      { id: "ifc-43", name: "Floor levels (RLs) noted on all plans", type: "pass_fail_flag", required: true },
      { id: "ifc-44", name: "Ceiling heights noted", type: "pass_fail_flag", required: true, description: "Finished ceiling heights including bulkheads and step-downs" },
      { id: "ifc-45", name: "Floor falls noted in wet areas", type: "pass_fail_flag", required: true, description: "Fall directions and gradients in bathrooms, laundries, balconies" },
      { id: "ifc-46", name: "Wall types correctly referenced", type: "pass_fail_flag", required: true, description: "Wall type tags match wall type schedule (fire rating, acoustic, wet area)" },
      { id: "ifc-47", name: "Door and window schedules up to date", type: "pass_fail_flag", required: true, description: "Schedules match plans - sizes, types, hardware, fire ratings" },
    ],
  },
  {
    id: "sec-ifc-6",
    name: "Finishes & Specifications",
    order: 5,
    description: "Verify finishes schedules and specification references",
    allowRepeats: false,
    items: [
      { id: "ifc-50", name: "Room finishes schedule complete", type: "pass_fail_flag", required: true, description: "Floor, wall, ceiling, skirting finishes for all rooms" },
      { id: "ifc-51", name: "External finishes schedule complete", type: "pass_fail_flag", required: true, description: "Facade materials, colours, and product references" },
      { id: "ifc-52", name: "Specification sections referenced on drawings", type: "pass_fail_flag", required: true, description: "Spec clause references for materials and workmanship" },
      { id: "ifc-53", name: "Waterproofing extents shown", type: "pass_fail_flag", required: true, description: "Wet area membranes, balcony waterproofing, podium decks per AS 3740" },
      { id: "ifc-54", name: "Tiling layout / set-out drawings provided", type: "yes_no_na", required: true, description: "Tile sizes, patterns, and setout for feature areas" },
      { id: "ifc-55", name: "External weather sealing details shown", type: "pass_fail_flag", required: true, description: "Window flashings, sill details, weatherproofing at junctions" },
    ],
  },
  {
    id: "sec-ifc-7",
    name: "Documentation Completeness",
    order: 6,
    description: "Verify the drawing set is complete and consistent",
    allowRepeats: false,
    items: [
      { id: "ifc-60", name: "Drawing list / index up to date", type: "pass_fail_flag", required: true, description: "Index matches all drawings in the set" },
      { id: "ifc-61", name: "All referenced details included in set", type: "pass_fail_flag", required: true, description: "No orphan detail references - all call-outs have corresponding details" },
      { id: "ifc-62", name: "All sections referenced and included", type: "pass_fail_flag", required: true, description: "Section markers on plans have corresponding section drawings" },
      { id: "ifc-63", name: "Key plan / location plans on detail sheets", type: "pass_fail_flag", required: true, description: "Detail sheets show location context" },
      { id: "ifc-64", name: "No preliminary or draft watermarks remaining", type: "pass_fail_flag", required: true, description: "All drawings correctly stamped as IFC - no draft marks" },
      { id: "ifc-65", name: "Superseded drawings list provided", type: "yes_no_na", required: true, description: "List of drawings superseded by this issue" },
      { id: "ifc-66", name: "Specification complete and current revision", type: "pass_fail_flag", required: true },
      { id: "ifc-67", name: "Transmittal prepared", type: "pass_fail_flag", required: true, description: "Formal transmittal listing all drawings, revisions, and purpose" },
    ],
  },
  {
    id: "sec-ifc-8",
    name: "Quality Assurance Sign-Off",
    order: 7,
    description: "Internal QA sign-off before issue to builder",
    allowRepeats: false,
    items: [
      { id: "ifc-70", name: "Internal peer review completed", type: "pass_fail_flag", required: true, description: "Drawing reviewed by another architect / team member" },
      { id: "ifc-71", name: "Design intent maintained from DA / CC drawings", type: "pass_fail_flag", required: true, description: "IFC drawings consistent with approved DA and CC documentation" },
      { id: "ifc-72", name: "All consultant comments incorporated", type: "pass_fail_flag", required: true, description: "Structural, services, and specialist consultant input addressed" },
      { id: "ifc-73", name: "Client / developer sign-off obtained", type: "yes_no_na", required: true, description: "Client has approved design before IFC issue (if required)" },
      { id: "ifc-74", name: "Review Outcome", type: "dropdown", required: true, options: ["Approved - Issue for Construction", "Approved with Comments - Amend Before Issue", "Not Approved - Further Review Required", "Hold - Awaiting Consultant Input"] },
      { id: "ifc-75", name: "Review Comments", type: "textarea", required: false, placeholder: "Detail any outstanding items, conditions, or notes for the issue" },
      { id: "ifc-76", name: "Reviewed By (QA Checker)", type: "text_field", required: true, placeholder: "Name of the person conducting QA review" },
      { id: "ifc-77", name: "QA Reviewer Signature", type: "signature_field", required: true },
      { id: "ifc-78", name: "Design Lead / Principal Authorisation", type: "signature_field", required: true, description: "Senior architect or principal sign-off authorising IFC issue" },
      { id: "ifc-79", name: "Authorisation Date", type: "datetime_field", required: true },
    ],
  },
];

export const DOCUMENT_TEMPLATE_DEFINITIONS = [
  {
    name: "Shop Drawing IFC - Precast",
    code: "SD_IFC_PRECAST",
    description: "IFC review checklist for precast concrete shop drawings. Covers geometry, reinforcement, cast-in items, finishes, cross-discipline coordination, and structural engineer sign-off per AS 3600 / AS 3850.",
    sections: SHOP_DRAWING_IFC_PRECAST_SECTIONS,
  },
  {
    name: "Shop Drawing IFC - Joinery",
    code: "SD_IFC_JOINERY",
    description: "IFC review checklist for joinery shop drawings. Covers dimensions, materials, finishes, hardware, services coordination, accessibility (AS 1428), and NCC wet area compliance.",
    sections: SHOP_DRAWING_JOINERY_SECTIONS,
  },
  {
    name: "Shop Drawing IFC - Stairs",
    code: "SD_IFC_STAIRS",
    description: "IFC review checklist for stair shop drawings. Covers BCA/NCC geometry compliance (going, riser, 2R+G), balustrade/handrail requirements (AS 1170.1), structural connections, fire rating, and accessibility (TGSIs, luminous markings).",
    sections: SHOP_DRAWING_STAIRS_SECTIONS,
  },
  {
    name: "IFC Checklist - Architectural Drawings",
    code: "IFC_ARCHITECTURAL",
    description: "Comprehensive IFC quality assurance checklist for architectural drawings. Enforces proper review process covering NCC/BCA compliance, cross-discipline coordination, dimensions, finishes, documentation completeness, and QA sign-off before issue to builder.",
    sections: IFC_ARCHITECTURAL_SECTIONS,
  },
];
