export const SITE_INDUCTION_SECTIONS = [
  {
    id: "sec-ind-1",
    name: "Inductee Details",
    order: 0,
    description: "Personal details and emergency contact information",
    allowRepeats: false,
    items: [
      { id: "ind-1", name: "Full Name", type: "text_field", required: true, placeholder: "Enter full name" },
      { id: "ind-2", name: "Company / Employer", type: "text_field", required: true, placeholder: "Company or subcontractor name" },
      { id: "ind-3", name: "Trade / Role", type: "text_field", required: true, placeholder: "e.g. Electrician, Labourer, Formworker" },
      { id: "ind-4", name: "Phone Number", type: "text_field", required: true, placeholder: "Mobile contact number" },
      { id: "ind-5", name: "Emergency Contact Name", type: "text_field", required: true, placeholder: "Emergency contact full name" },
      { id: "ind-6", name: "Emergency Contact Phone", type: "text_field", required: true, placeholder: "Emergency contact phone number" },
      { id: "ind-7", name: "White Card / Construction Card Number", type: "text_field", required: true, placeholder: "General Construction Induction card number" },
      { id: "ind-8", name: "White Card Sighted", type: "pass_fail_flag", required: true, description: "Has the White Card / Construction Induction Card been physically sighted?" },
      { id: "ind-9", name: "Photo ID Sighted", type: "pass_fail_flag", required: true, description: "Has a valid photo identification been sighted?" },
    ],
  },
  {
    id: "sec-ind-2",
    name: "Site-Specific Information",
    order: 1,
    description: "Key site information communicated during induction",
    allowRepeats: false,
    items: [
      { id: "ind-10", name: "Project Name & Address", type: "text_field", required: true, placeholder: "Project name and street address" },
      { id: "ind-11", name: "Principal Contractor", type: "text_field", required: true, placeholder: "Head contractor / builder" },
      { id: "ind-12", name: "Site Entry/Exit Points Explained", type: "yes_no_na", required: true, description: "Worker shown where to enter and exit the site" },
      { id: "ind-13", name: "Sign-In/Out Procedures Explained", type: "yes_no_na", required: true, description: "Sign-in/out and visitor log requirements explained" },
      { id: "ind-14", name: "Working Hours Communicated", type: "yes_no_na", required: true, description: "Standard working hours and noise curfew times" },
      { id: "ind-15", name: "Speed Limits & Traffic Management", type: "yes_no_na", required: true, description: "On-site speed limits, traffic routes, and pedestrian zones" },
      { id: "ind-16", name: "Parking Arrangements", type: "yes_no_na", required: true, description: "Where workers can and cannot park" },
    ],
  },
  {
    id: "sec-ind-3",
    name: "Emergency Procedures",
    order: 2,
    description: "Emergency response procedures and locations",
    allowRepeats: false,
    items: [
      { id: "ind-20", name: "Emergency Assembly Point Location", type: "yes_no_na", required: true, description: "Worker shown the emergency assembly/muster point" },
      { id: "ind-21", name: "Emergency Evacuation Procedure", type: "yes_no_na", required: true, description: "Evacuation alarm, routes, and procedures explained" },
      { id: "ind-22", name: "First Aid Station Location", type: "yes_no_na", required: true, description: "Worker shown the first aid station and first aid officers" },
      { id: "ind-23", name: "Fire Extinguisher Locations", type: "yes_no_na", required: true, description: "Shown locations of fire extinguishers and hose reels" },
      { id: "ind-24", name: "Emergency Contact Numbers Provided", type: "yes_no_na", required: true, description: "Site emergency phone numbers and reporting chain" },
      { id: "ind-25", name: "Incident Reporting Procedure", type: "yes_no_na", required: true, description: "How to report incidents, near misses, and injuries" },
    ],
  },
  {
    id: "sec-ind-4",
    name: "Safety Requirements",
    order: 3,
    description: "PPE and general safety requirements on site",
    allowRepeats: false,
    items: [
      { id: "ind-30", name: "Mandatory PPE Requirements Explained", type: "yes_no_na", required: true, description: "Hard hat, hi-vis, safety boots, safety glasses as minimum" },
      { id: "ind-31", name: "Task-Specific PPE Requirements", type: "yes_no_na", required: true, description: "Hearing protection, gloves, respirators, harnesses as required" },
      { id: "ind-32", name: "Working at Heights Requirements", type: "yes_no_na", required: true, description: "Fall protection, edge protection, harness use requirements" },
      { id: "ind-33", name: "Exclusion Zones & Barricading", type: "yes_no_na", required: true, description: "Drop zones, crane exclusion zones, and barricaded areas" },
      { id: "ind-34", name: "Permit-to-Work System", type: "yes_no_na", required: true, description: "Hot works, confined space, excavation, and other permits" },
      { id: "ind-35", name: "Housekeeping Standards", type: "yes_no_na", required: true, description: "Clean-as-you-go policy, waste management, and skip bins" },
      { id: "ind-36", name: "Drug & Alcohol Policy", type: "yes_no_na", required: true, description: "Zero tolerance policy and testing procedures" },
      { id: "ind-37", name: "Fitness for Work", type: "yes_no_na", required: true, description: "Fatigue management and fitness for work obligations" },
      { id: "ind-38", name: "Mobile Phone Policy", type: "yes_no_na", required: true, description: "Restrictions on mobile phone use in work areas" },
    ],
  },
  {
    id: "sec-ind-5",
    name: "High-Rise Specific",
    order: 4,
    description: "Additional requirements for high-rise construction",
    allowRepeats: false,
    items: [
      { id: "ind-40", name: "Hoist / Lift Procedures", type: "yes_no_na", required: true, description: "Personnel and materials hoist procedures and capacity limits" },
      { id: "ind-41", name: "Edge Protection & Penetrations", type: "yes_no_na", required: true, description: "Requirements around slab edges, penetrations, and voids" },
      { id: "ind-42", name: "Wind Speed Restrictions", type: "yes_no_na", required: true, description: "Work cessation procedures during high wind events" },
      { id: "ind-43", name: "Crane Operations Awareness", type: "yes_no_na", required: true, description: "Crane swing radius, load paths, and communication signals" },
      { id: "ind-44", name: "Material Storage on Floors", type: "yes_no_na", required: true, description: "Load limits per floor and material storage requirements" },
      { id: "ind-45", name: "Perimeter Containment Screens", type: "yes_no_na", required: true, description: "Purpose and restrictions around containment/scaffold screens" },
    ],
  },
  {
    id: "sec-ind-6",
    name: "Acknowledgement & Sign-off",
    order: 5,
    description: "Worker acknowledgement and inductor sign-off",
    allowRepeats: false,
    items: [
      { id: "ind-50", name: "Worker Understands Site Rules", type: "pass_fail_flag", required: true, description: "Worker confirms they understand all site rules and requirements" },
      { id: "ind-51", name: "Worker Questions Addressed", type: "yes_no_na", required: true, description: "All questions from the worker have been answered" },
      { id: "ind-52", name: "Inductee Signature", type: "signature_field", required: true, description: "Worker signature confirming induction completion" },
      { id: "ind-53", name: "Inductor Name", type: "text_field", required: true, placeholder: "Name of person conducting induction" },
      { id: "ind-54", name: "Inductor Signature", type: "signature_field", required: true, description: "Inductor signature confirming induction delivered" },
      { id: "ind-55", name: "Induction Date", type: "date_field", required: true, description: "Date induction was completed" },
      { id: "ind-56", name: "Induction Expiry", type: "date_field", required: false, description: "Date this induction expires (if applicable)" },
    ],
  },
];

export const SAFETY_WALK_SECTIONS = [
  {
    id: "sec-sw-1",
    name: "Walk Details",
    order: 0,
    description: "General information about the safety walk",
    allowRepeats: false,
    items: [
      { id: "sw-1", name: "Walk Date & Time", type: "datetime_field", required: true, description: "When the safety walk was conducted" },
      { id: "sw-2", name: "Walk Leader", type: "staff_assignment", required: true, description: "Person conducting the safety walk" },
      { id: "sw-3", name: "Walk Participants", type: "textarea", required: false, placeholder: "List all walk participants and their roles" },
      { id: "sw-4", name: "Areas Inspected", type: "textarea", required: true, placeholder: "e.g. Levels 5-8, basement car park, tower crane base" },
      { id: "sw-5", name: "Weather Conditions", type: "dropdown", required: true, options: [{ text: "Fine/Clear", value: "fine" }, { text: "Overcast", value: "overcast" }, { text: "Light Rain", value: "light_rain" }, { text: "Heavy Rain", value: "heavy_rain" }, { text: "Windy", value: "windy" }, { text: "Extreme Heat", value: "extreme_heat" }], description: "Current weather conditions" },
    ],
  },
  {
    id: "sec-sw-2",
    name: "Housekeeping & Access",
    order: 1,
    description: "General housekeeping and site access assessment",
    allowRepeats: false,
    items: [
      { id: "sw-10", name: "Site Entry/Exit Clear & Controlled", type: "inspection_check", required: true, description: "Access points clear, gates secured, sign-in operational" },
      { id: "sw-11", name: "Walkways & Corridors Clear", type: "inspection_check", required: true, description: "No obstructions, trip hazards, or stored materials in walkways" },
      { id: "sw-12", name: "Work Areas Clean & Tidy", type: "inspection_check", required: true, description: "Rubbish removed, materials stacked properly, no debris" },
      { id: "sw-13", name: "Waste Management", type: "inspection_check", required: true, description: "Skip bins available, not overflowing, waste segregated" },
      { id: "sw-14", name: "Lighting Adequate", type: "inspection_check", required: true, description: "Sufficient lighting in all work areas and access routes" },
      { id: "sw-15", name: "Signage & Barricading", type: "inspection_check", required: true, description: "Safety signs visible, barricades in place where needed" },
    ],
  },
  {
    id: "sec-sw-3",
    name: "PPE Compliance",
    order: 2,
    description: "Personal protective equipment compliance check",
    allowRepeats: false,
    items: [
      { id: "sw-20", name: "Hard Hats Worn Correctly", type: "inspection_check", required: true, description: "All workers wearing hard hats in designated areas" },
      { id: "sw-21", name: "Hi-Vis Vests/Clothing", type: "inspection_check", required: true, description: "All workers wearing hi-vis in required areas" },
      { id: "sw-22", name: "Safety Footwear", type: "inspection_check", required: true, description: "Steel-capped boots worn by all workers" },
      { id: "sw-23", name: "Safety Glasses/Eye Protection", type: "inspection_check", required: true, description: "Eye protection worn where required" },
      { id: "sw-24", name: "Task-Specific PPE", type: "inspection_check", required: true, description: "Gloves, hearing protection, respirators worn as required" },
      { id: "sw-25", name: "PPE in Good Condition", type: "inspection_check", required: true, description: "All PPE serviceable and not damaged" },
    ],
  },
  {
    id: "sec-sw-4",
    name: "Fall Prevention",
    order: 3,
    description: "Fall protection and edge protection assessment",
    allowRepeats: false,
    items: [
      { id: "sw-30", name: "Edge Protection in Place", type: "inspection_check", required: true, description: "Guardrails, toe boards at all open edges" },
      { id: "sw-31", name: "Penetrations Covered/Protected", type: "inspection_check", required: true, description: "Floor penetrations, stairwells, and voids covered or barricaded" },
      { id: "sw-32", name: "Scaffold in Good Condition", type: "inspection_check", required: true, description: "Scaffold tagged, complete, and no modifications" },
      { id: "sw-33", name: "Ladders Used Correctly", type: "inspection_check", required: true, description: "Ladders secured, correct angle, not damaged" },
      { id: "sw-34", name: "Harnesses Worn Where Required", type: "inspection_check", required: true, description: "Workers using fall arrest where edge protection not possible" },
      { id: "sw-35", name: "Drop Zone Controls", type: "inspection_check", required: true, description: "Drop zones barricaded with signage, no workers underneath" },
    ],
  },
  {
    id: "sec-sw-5",
    name: "Plant & Equipment",
    order: 4,
    description: "Plant, equipment, and electrical safety",
    allowRepeats: false,
    items: [
      { id: "sw-40", name: "Plant Pre-Start Checks Completed", type: "inspection_check", required: true, description: "Pre-start checklists completed for all plant" },
      { id: "sw-41", name: "Exclusion Zones Established", type: "inspection_check", required: true, description: "Plant exclusion zones marked and enforced" },
      { id: "sw-42", name: "Electrical Leads & Equipment Tagged", type: "inspection_check", required: true, description: "All electrical leads and tools have current test tags" },
      { id: "sw-43", name: "RCDs in Use", type: "inspection_check", required: true, description: "Residual current devices in use for all portable equipment" },
      { id: "sw-44", name: "Crane Operations Safe", type: "inspection_check", required: true, description: "Crane operations following safe work procedures" },
      { id: "sw-45", name: "Fire Extinguishers Accessible", type: "inspection_check", required: true, description: "Fire extinguishers in place, serviced, and unobstructed" },
    ],
  },
  {
    id: "sec-sw-6",
    name: "Hazardous Materials",
    order: 5,
    description: "Chemical storage and hazardous materials management",
    allowRepeats: false,
    items: [
      { id: "sw-50", name: "SDS Available", type: "inspection_check", required: true, description: "Safety Data Sheets available for all chemicals on site" },
      { id: "sw-51", name: "Chemical Storage Correct", type: "inspection_check", required: true, description: "Chemicals stored in bunded area with correct segregation" },
      { id: "sw-52", name: "Spill Kits Available", type: "inspection_check", required: true, description: "Spill kits accessible and fully stocked" },
      { id: "sw-53", name: "Asbestos Register Checked", type: "inspection_check", required: false, description: "Asbestos register reviewed if applicable to existing structures" },
    ],
  },
  {
    id: "sec-sw-7",
    name: "Observations & Actions",
    order: 6,
    description: "Record observations and corrective actions",
    allowRepeats: true,
    items: [
      { id: "sw-60", name: "Observation Photo", type: "multi_photo", required: false, description: "Photo evidence of finding" },
      { id: "sw-61", name: "Observation Description", type: "textarea", required: true, placeholder: "Describe the safety observation or hazard" },
      { id: "sw-62", name: "Risk Level", type: "dropdown", required: true, options: [{ text: "Low - Minor Improvement", value: "low" }, { text: "Medium - Action Required", value: "medium" }, { text: "High - Immediate Action", value: "high" }, { text: "Critical - Stop Work", value: "critical" }] },
      { id: "sw-63", name: "Corrective Action Required", type: "textarea", required: true, placeholder: "Describe the corrective action needed" },
      { id: "sw-64", name: "Responsible Person", type: "staff_assignment", required: false, description: "Person responsible for corrective action" },
      { id: "sw-65", name: "Due Date", type: "date_field", required: false, description: "Date corrective action must be completed" },
    ],
  },
  {
    id: "sec-sw-8",
    name: "Walk Summary & Sign-off",
    order: 7,
    description: "Overall assessment and walk sign-off",
    allowRepeats: false,
    items: [
      { id: "sw-70", name: "Overall Site Safety Rating", type: "rating_scale", required: true, min: 1, max: 5, description: "Rate overall site safety condition 1-5" },
      { id: "sw-71", name: "Total Observations", type: "number_field", required: false, placeholder: "Number of observations recorded" },
      { id: "sw-72", name: "Walk Summary Comments", type: "textarea", required: false, placeholder: "Overall comments and key findings from the walk" },
      { id: "sw-73", name: "Walk Leader Signature", type: "signature_field", required: true, description: "Walk leader sign-off" },
    ],
  },
];

export const DROP_ZONE_SECTIONS = [
  {
    id: "sec-dz-1",
    name: "Drop Zone Details",
    order: 0,
    description: "Location and scope of the drop zone",
    allowRepeats: false,
    items: [
      { id: "dz-1", name: "Drop Zone Location", type: "text_field", required: true, placeholder: "e.g. North elevation, Gridline A-C, Levels 3-8" },
      { id: "dz-2", name: "Date & Time Established", type: "datetime_field", required: true, description: "When the drop zone was established" },
      { id: "dz-3", name: "Reason for Drop Zone", type: "dropdown", required: true, options: [{ text: "Crane Lifting Operations", value: "crane" }, { text: "Formwork Stripping", value: "formwork" }, { text: "Edge Work / Façade Installation", value: "edge_work" }, { text: "Demolition Works", value: "demolition" }, { text: "Scaffold Erection / Dismantle", value: "scaffold" }, { text: "Window / Glazing Installation", value: "glazing" }, { text: "Concrete Pour", value: "concrete" }, { text: "Other", value: "other" }] },
      { id: "dz-4", name: "Other Reason Details", type: "text_field", required: false, placeholder: "Specify if Other selected" },
      { id: "dz-5", name: "Estimated Duration", type: "text_field", required: true, placeholder: "e.g. 4 hours, full day, 3 days" },
      { id: "dz-6", name: "Responsible Supervisor", type: "staff_assignment", required: true, description: "Supervisor responsible for maintaining the drop zone" },
    ],
  },
  {
    id: "sec-dz-2",
    name: "Barricading & Signage",
    order: 1,
    description: "Physical barriers and warning signage in place",
    allowRepeats: false,
    items: [
      { id: "dz-10", name: "Hard Barricades Installed", type: "pass_fail_flag", required: true, description: "Solid barricades (not tape alone) around the entire drop zone perimeter" },
      { id: "dz-11", name: "Barricade Height Minimum 1.0m", type: "pass_fail_flag", required: true, description: "Barricades at least 1 metre high" },
      { id: "dz-12", name: "Drop Zone Signage Displayed", type: "pass_fail_flag", required: true, description: "DANGER - DROP ZONE signs visible on all approaches" },
      { id: "dz-13", name: "Flashing Lights Installed", type: "yes_no_na", required: true, description: "Flashing warning lights where required (e.g. near high-traffic areas)" },
      { id: "dz-14", name: "No Public Access Possible", type: "pass_fail_flag", required: true, description: "Public footpaths and adjacent areas protected or diverted" },
      { id: "dz-15", name: "Adjacent Entries Blocked or Managed", type: "pass_fail_flag", required: true, description: "No uncontrolled access to drop zone from building entries or stairwells" },
      { id: "dz-16", name: "Barricading Photos", type: "multi_photo", required: false, description: "Photographs showing all barricading and signage" },
    ],
  },
  {
    id: "sec-dz-3",
    name: "Overhead Protection",
    order: 2,
    description: "Catch platforms and overhead protection assessment",
    allowRepeats: false,
    items: [
      { id: "dz-20", name: "Catch Platform / Overhead Protection Required", type: "yes_no_na", required: true, description: "Is overhead protection needed based on risk assessment?" },
      { id: "dz-21", name: "Catch Platform Installed", type: "yes_no_na", required: false, description: "Catch platform or fan installed at appropriate level" },
      { id: "dz-22", name: "Catch Platform Engineered", type: "yes_no_na", required: false, description: "Catch platform designed/certified by engineer" },
      { id: "dz-23", name: "Debris Netting in Place", type: "yes_no_na", required: true, description: "Containment screens or debris netting installed" },
      { id: "dz-24", name: "Toe Boards on Upper Levels", type: "yes_no_na", required: true, description: "Toe boards installed to prevent tools/materials falling" },
    ],
  },
  {
    id: "sec-dz-4",
    name: "Communication & Monitoring",
    order: 3,
    description: "Communication plan and ongoing monitoring",
    allowRepeats: false,
    items: [
      { id: "dz-30", name: "All Workers Notified (Toolbox Talk)", type: "pass_fail_flag", required: true, description: "All site workers advised of drop zone location and restrictions" },
      { id: "dz-31", name: "Spotter / Banksman Assigned", type: "yes_no_na", required: true, description: "Dedicated spotter managing ground-level access during operations" },
      { id: "dz-32", name: "Two-Way Radio Communication", type: "yes_no_na", required: true, description: "Radio communication between upper levels and ground level" },
      { id: "dz-33", name: "Regular Monitoring Schedule", type: "yes_no_na", required: true, description: "Periodic checks scheduled to verify barricading integrity" },
      { id: "dz-34", name: "Wind Speed Monitoring", type: "yes_no_na", required: false, description: "Wind speed being monitored for crane/lifting operations" },
    ],
  },
  {
    id: "sec-dz-5",
    name: "Sign-off",
    order: 4,
    description: "Approval and sign-off for drop zone activation",
    allowRepeats: false,
    items: [
      { id: "dz-40", name: "Drop Zone Approved to Activate", type: "pass_fail_flag", required: true, description: "All controls verified and drop zone approved for use" },
      { id: "dz-41", name: "SWMS Reviewed", type: "pass_fail_flag", required: true, description: "Safe Work Method Statement reviewed and signed by workers" },
      { id: "dz-42", name: "Supervisor Signature", type: "signature_field", required: true, description: "Supervisor confirming drop zone setup is compliant" },
      { id: "dz-43", name: "Safety Officer Review", type: "signature_field", required: false, description: "Safety officer review and sign-off if required" },
    ],
  },
];

export const CRANE_JUMP_SECTIONS = [
  {
    id: "sec-cj-1",
    name: "Crane & Jump Details",
    order: 0,
    description: "Crane identification and jump operation information",
    allowRepeats: false,
    items: [
      { id: "cj-1", name: "Crane ID / Number", type: "text_field", required: true, placeholder: "e.g. TC-01, Tower Crane 1" },
      { id: "cj-2", name: "Crane Make & Model", type: "text_field", required: true, placeholder: "e.g. Liebherr 280 EC-H" },
      { id: "cj-3", name: "Maximum Capacity (tonnes)", type: "number_field", required: true, placeholder: "Maximum lifting capacity" },
      { id: "cj-4", name: "Current Height (metres)", type: "number_field", required: true, placeholder: "Current crane height before jump" },
      { id: "cj-5", name: "Target Height After Jump (metres)", type: "number_field", required: true, placeholder: "Target crane height after jump" },
      { id: "cj-6", name: "Jump Section Height (metres)", type: "number_field", required: true, placeholder: "Height of each mast section" },
      { id: "cj-7", name: "Number of Sections to Add", type: "number_field", required: true, placeholder: "How many mast sections being added" },
      { id: "cj-8", name: "Planned Jump Date", type: "date_field", required: true, description: "Scheduled date for the jump operation" },
      { id: "cj-9", name: "Crane Crew Supervisor", type: "staff_assignment", required: true, description: "Lead crane technician/rigger for the jump" },
    ],
  },
  {
    id: "sec-cj-2",
    name: "Pre-Jump Engineering",
    order: 1,
    description: "Engineering reviews and documentation verification",
    allowRepeats: false,
    items: [
      { id: "cj-10", name: "Crane Jump Procedure Reviewed", type: "pass_fail_flag", required: true, description: "Manufacturer's jump procedure document reviewed by crew" },
      { id: "cj-11", name: "Structural Engineer Certification Current", type: "pass_fail_flag", required: true, description: "Engineer has certified crane base/tie-backs for increased height" },
      { id: "cj-12", name: "Tie-Back / Brace Design Verified", type: "pass_fail_flag", required: true, description: "Tie-back locations and brace design verified against engineer drawings" },
      { id: "cj-13", name: "Foundation / Base Adequacy Confirmed", type: "pass_fail_flag", required: true, description: "Foundation loads confirmed adequate for new crane height" },
      { id: "cj-14", name: "New Tie-Back Level Prepared", type: "pass_fail_flag", required: true, description: "Cast-in anchors and tie-back connection points ready" },
      { id: "cj-15", name: "Climbing Frame Condition Inspected", type: "pass_fail_flag", required: true, description: "Hydraulic climbing frame inspected and serviceable" },
      { id: "cj-16", name: "Crane Maintenance Log Current", type: "pass_fail_flag", required: true, description: "All routine maintenance up to date, no outstanding defects" },
    ],
  },
  {
    id: "sec-cj-3",
    name: "Pre-Jump Safety Checks",
    order: 2,
    description: "Safety checks before commencing the jump",
    allowRepeats: false,
    items: [
      { id: "cj-20", name: "Weather Forecast Checked", type: "pass_fail_flag", required: true, description: "BOM forecast checked - no adverse weather predicted during jump window" },
      { id: "cj-21", name: "Wind Speed Below Limit", type: "pass_fail_flag", required: true, description: "Current and forecast wind speed below manufacturer's limit for jumping" },
      { id: "cj-22", name: "Wind Speed Reading (km/h)", type: "number_field", required: true, placeholder: "Current wind speed at crane height" },
      { id: "cj-23", name: "Exclusion Zone Established", type: "pass_fail_flag", required: true, description: "Ground-level exclusion zone barricaded and signed" },
      { id: "cj-24", name: "All Loads Removed from Crane", type: "pass_fail_flag", required: true, description: "Hook block lowered, no slings or loads attached" },
      { id: "cj-25", name: "Jib in Correct Position", type: "pass_fail_flag", required: true, description: "Jib positioned per manufacturer's jump procedure" },
      { id: "cj-26", name: "Counter-Jib Ballast Correct", type: "pass_fail_flag", required: true, description: "Counter-weight configuration correct for jumping" },
      { id: "cj-27", name: "Mast Sections Staged & Inspected", type: "pass_fail_flag", required: true, description: "New mast sections on site, inspected for damage, bolts checked" },
      { id: "cj-28", name: "Hydraulic System Pre-Check", type: "pass_fail_flag", required: true, description: "Hydraulic fluid levels, hoses, cylinders, and pump inspected" },
      { id: "cj-29", name: "All Electrical Isolations in Place", type: "pass_fail_flag", required: true, description: "Slewing and travel drives locked out as per procedure" },
    ],
  },
  {
    id: "sec-cj-4",
    name: "Personnel & Communication",
    order: 3,
    description: "Crew verification and communication check",
    allowRepeats: false,
    items: [
      { id: "cj-30", name: "All Crew Hold Current Licences", type: "pass_fail_flag", required: true, description: "Dogger, rigger, and crane crew licences sighted and current" },
      { id: "cj-31", name: "Crew Toolbox Talk Completed", type: "pass_fail_flag", required: true, description: "All crew briefed on procedure, emergency plan, and roles" },
      { id: "cj-32", name: "Spotter / Banksman in Position", type: "pass_fail_flag", required: true, description: "Ground-level spotter managing exclusion zone" },
      { id: "cj-33", name: "Two-Way Radio Check", type: "pass_fail_flag", required: true, description: "Radio communication verified between all positions" },
      { id: "cj-34", name: "Emergency Rescue Plan in Place", type: "pass_fail_flag", required: true, description: "Rescue plan and equipment available for personnel at height" },
      { id: "cj-35", name: "Adjacent Crane(s) Notified", type: "yes_no_na", required: true, description: "If other cranes on site, operators notified of jump and swing restrictions" },
      { id: "cj-36", name: "Site Manager / PM Notified", type: "pass_fail_flag", required: true, description: "Site management aware of jump schedule" },
    ],
  },
  {
    id: "sec-cj-5",
    name: "During Jump Monitoring",
    order: 4,
    description: "Checks during the climbing/jumping operation",
    allowRepeats: false,
    items: [
      { id: "cj-40", name: "Climbing Frame Operation Smooth", type: "pass_fail_flag", required: true, description: "Hydraulic climbing frame operating correctly without binding" },
      { id: "cj-41", name: "Mast Section Alignment Correct", type: "pass_fail_flag", required: true, description: "New mast sections aligning correctly during insertion" },
      { id: "cj-42", name: "Bolt Torques Applied Per Spec", type: "pass_fail_flag", required: true, description: "All mast connection bolts torqued to manufacturer specification" },
      { id: "cj-43", name: "Plumb/Verticality Checked", type: "pass_fail_flag", required: true, description: "Crane mast verticality verified during and after section addition" },
      { id: "cj-44", name: "No Unusual Noises or Vibrations", type: "pass_fail_flag", required: true, description: "No abnormal sounds, vibrations, or movement during jump" },
      { id: "cj-45", name: "Wind Conditions Still Acceptable", type: "pass_fail_flag", required: true, description: "Wind speed re-checked and still within limits" },
    ],
  },
  {
    id: "sec-cj-6",
    name: "Post-Jump Checks",
    order: 5,
    description: "Verification checks after jump completion",
    allowRepeats: false,
    items: [
      { id: "cj-50", name: "All Mast Bolts Final Torqued", type: "pass_fail_flag", required: true, description: "Final torque check on all new mast section bolts" },
      { id: "cj-51", name: "Tie-Backs Connected & Pinned", type: "pass_fail_flag", required: true, description: "New tie-back/braces connected and all pins/bolts secured" },
      { id: "cj-52", name: "Crane Verticality Final Check", type: "pass_fail_flag", required: true, description: "Final plumb/verticality measurement within tolerance" },
      { id: "cj-53", name: "Slewing Test Completed", type: "pass_fail_flag", required: true, description: "Full 360° slew test completed without obstruction" },
      { id: "cj-54", name: "Hoist Test Completed", type: "pass_fail_flag", required: true, description: "Load hoist tested at reduced capacity" },
      { id: "cj-55", name: "All Safety Devices Reset & Tested", type: "pass_fail_flag", required: true, description: "Limit switches, anemometer, anti-collision recalibrated" },
      { id: "cj-56", name: "Climbing Frame Stowed", type: "pass_fail_flag", required: true, description: "Climbing frame retracted and secured" },
      { id: "cj-57", name: "Exclusion Zone Removed", type: "pass_fail_flag", required: true, description: "Ground-level exclusion zone dismantled after all-clear" },
      { id: "cj-58", name: "Post-Jump Photos", type: "multi_photo", required: false, description: "Photographs of completed jump showing tie-backs and mast" },
    ],
  },
  {
    id: "sec-cj-7",
    name: "Sign-off & Return to Service",
    order: 6,
    description: "Final approvals for crane return to service",
    allowRepeats: false,
    items: [
      { id: "cj-60", name: "Crane Approved for Return to Service", type: "pass_fail_flag", required: true, description: "All checks passed, crane approved for normal operations" },
      { id: "cj-61", name: "Crane Log Book Updated", type: "pass_fail_flag", required: true, description: "Jump recorded in crane maintenance/log book" },
      { id: "cj-62", name: "New Height Recorded (metres)", type: "number_field", required: true, placeholder: "Final crane height after jump" },
      { id: "cj-63", name: "Crane Technician Signature", type: "signature_field", required: true, description: "Lead crane technician sign-off" },
      { id: "cj-64", name: "Site Safety Officer Signature", type: "signature_field", required: false, description: "Safety officer sign-off (if required)" },
      { id: "cj-65", name: "Structural Engineer Sign-off Required", type: "yes_no_na", required: true, description: "Does the structural engineer need to inspect before return to service?" },
    ],
  },
];

export const HOT_WORKS_SECTIONS = [
  {
    id: "sec-hw-1",
    name: "Permit Details",
    order: 0,
    description: "Hot works permit identification and scope",
    allowRepeats: false,
    items: [
      { id: "hw-1", name: "Permit Number", type: "text_field", required: true, placeholder: "Hot works permit reference number" },
      { id: "hw-2", name: "Date & Time Issued", type: "datetime_field", required: true, description: "When the permit was issued" },
      { id: "hw-3", name: "Permit Expiry Date & Time", type: "datetime_field", required: true, description: "When the permit expires (max 24 hours)" },
      { id: "hw-4", name: "Location of Hot Works", type: "text_field", required: true, placeholder: "e.g. Level 5, Gridline C-D, column connection" },
      { id: "hw-5", name: "Type of Hot Works", type: "dropdown", required: true, options: [{ text: "Welding (MIG/TIG/Stick)", value: "welding" }, { text: "Oxy-Acetylene Cutting", value: "oxy_cutting" }, { text: "Grinding / Cutting Disc", value: "grinding" }, { text: "Brazing / Soldering", value: "brazing" }, { text: "Bituminous/Torch-On Roofing", value: "torch_on" }, { text: "Other Heat-Producing Work", value: "other" }] },
      { id: "hw-6", name: "Description of Work", type: "textarea", required: true, placeholder: "Describe the specific hot works to be performed" },
      { id: "hw-7", name: "Worker Performing Hot Works", type: "text_field", required: true, placeholder: "Name of person performing the work" },
      { id: "hw-8", name: "Fire Watch Person", type: "text_field", required: true, placeholder: "Name of dedicated fire watch" },
    ],
  },
  {
    id: "sec-hw-2",
    name: "Pre-Work Checks",
    order: 1,
    description: "Safety checks before commencing hot works",
    allowRepeats: false,
    items: [
      { id: "hw-10", name: "Combustibles Removed (10m radius)", type: "pass_fail_flag", required: true, description: "All combustible materials removed or protected within 10 metres" },
      { id: "hw-11", name: "Non-Removable Combustibles Covered", type: "pass_fail_flag", required: true, description: "Fire-resistant blankets/shields covering items that cannot be moved" },
      { id: "hw-12", name: "Floor Openings / Gaps Sealed", type: "pass_fail_flag", required: true, description: "Floor penetrations and gaps sealed to prevent sparks falling below" },
      { id: "hw-13", name: "Levels Below Checked & Protected", type: "pass_fail_flag", required: true, description: "Areas below hot works checked for combustibles and protected" },
      { id: "hw-14", name: "Fire Extinguisher at Work Location", type: "pass_fail_flag", required: true, description: "Minimum one charged fire extinguisher within 5 metres" },
      { id: "hw-15", name: "Fire Blanket Available", type: "pass_fail_flag", required: true, description: "Fire blanket available at the work location" },
      { id: "hw-16", name: "Smoke/Fire Detection Isolated (if required)", type: "yes_no_na", required: true, description: "Local fire detection isolated with building manager approval" },
      { id: "hw-17", name: "Ventilation Adequate", type: "pass_fail_flag", required: true, description: "Adequate ventilation for fume extraction" },
      { id: "hw-18", name: "Gas Cylinders Secure & Upright", type: "yes_no_na", required: true, description: "Gas cylinders chained, upright, and flashback arrestors fitted" },
      { id: "hw-19", name: "Welding Screens in Place", type: "pass_fail_flag", required: true, description: "Welding screens erected to protect other workers" },
    ],
  },
  {
    id: "sec-hw-3",
    name: "PPE & Qualifications",
    order: 2,
    description: "Worker PPE and qualification checks",
    allowRepeats: false,
    items: [
      { id: "hw-20", name: "Welding Helmet/Shield", type: "pass_fail_flag", required: true, description: "Correct shade welding helmet or shield available" },
      { id: "hw-21", name: "Fire-Resistant Clothing", type: "pass_fail_flag", required: true, description: "Long sleeves, leather apron/jacket, no synthetic fabrics" },
      { id: "hw-22", name: "Welding Gloves", type: "pass_fail_flag", required: true, description: "Appropriate heat-resistant gloves" },
      { id: "hw-23", name: "Safety Boots (Lace-Up)", type: "pass_fail_flag", required: true, description: "Lace-up leather safety boots (not slip-on)" },
      { id: "hw-24", name: "Respirator (if required)", type: "yes_no_na", required: true, description: "Fume respirator if working in confined/poorly ventilated area" },
      { id: "hw-25", name: "Current Trade Qualification", type: "pass_fail_flag", required: true, description: "Worker holds current qualification for the hot works being performed" },
    ],
  },
  {
    id: "sec-hw-4",
    name: "Post-Work Fire Watch",
    order: 3,
    description: "Fire watch requirements after hot works cease",
    allowRepeats: false,
    items: [
      { id: "hw-30", name: "Hot Works Ceased Time", type: "datetime_field", required: true, description: "Time hot works were completed" },
      { id: "hw-31", name: "Fire Watch Duration (minimum 60 min)", type: "pass_fail_flag", required: true, description: "Fire watch maintained for minimum 60 minutes after hot works ceased" },
      { id: "hw-32", name: "Area Checked for Smouldering", type: "pass_fail_flag", required: true, description: "Work area and surrounding areas checked for smouldering materials" },
      { id: "hw-33", name: "Levels Below Re-Checked", type: "pass_fail_flag", required: true, description: "Levels below re-inspected after fire watch period" },
      { id: "hw-34", name: "Fire Detection Re-Activated", type: "yes_no_na", required: true, description: "Smoke/fire detection systems reinstated if previously isolated" },
      { id: "hw-35", name: "Fire Watch Completion Signature", type: "signature_field", required: true, description: "Fire watch person sign-off confirming area safe" },
    ],
  },
  {
    id: "sec-hw-5",
    name: "Permit Authorisation",
    order: 4,
    description: "Permit sign-off and authorisation",
    allowRepeats: false,
    items: [
      { id: "hw-40", name: "Permit Issuer Name", type: "text_field", required: true, placeholder: "Name of person issuing the permit" },
      { id: "hw-41", name: "Permit Issuer Signature", type: "signature_field", required: true, description: "Issuer authorisation signature" },
      { id: "hw-42", name: "Worker Acknowledgement Signature", type: "signature_field", required: true, description: "Worker confirms understanding of all conditions" },
    ],
  },
];

export const WORKING_AT_HEIGHTS_SECTIONS = [
  {
    id: "sec-wah-1",
    name: "Task Details",
    order: 0,
    description: "Details of the work at heights task",
    allowRepeats: false,
    items: [
      { id: "wah-1", name: "Date & Time", type: "datetime_field", required: true },
      { id: "wah-2", name: "Location / Level", type: "text_field", required: true, placeholder: "e.g. Level 12 slab edge, lift shaft, stairwell" },
      { id: "wah-3", name: "Height Above Ground (metres)", type: "number_field", required: true, placeholder: "Working height above ground/lower level" },
      { id: "wah-4", name: "Task Description", type: "textarea", required: true, placeholder: "Describe the work to be performed at height" },
      { id: "wah-5", name: "Fall Protection Method", type: "dropdown", required: true, options: [{ text: "Guardrails / Edge Protection", value: "guardrails" }, { text: "Safety Net", value: "safety_net" }, { text: "Scaffold", value: "scaffold" }, { text: "EWP / Boom Lift", value: "ewp" }, { text: "Fall Arrest Harness & Lanyard", value: "harness" }, { text: "Travel Restraint System", value: "travel_restraint" }, { text: "Combination of Systems", value: "combination" }] },
      { id: "wah-6", name: "SWMS Reference", type: "text_field", required: true, placeholder: "SWMS document reference number" },
    ],
  },
  {
    id: "sec-wah-2",
    name: "Edge Protection / Guardrails",
    order: 1,
    description: "Edge protection system checks",
    allowRepeats: false,
    items: [
      { id: "wah-10", name: "Top Rail at 900-1100mm", type: "inspection_check", required: true, description: "Top guardrail installed between 900mm and 1100mm height" },
      { id: "wah-11", name: "Mid Rail Installed", type: "inspection_check", required: true, description: "Mid rail installed to prevent person passing through" },
      { id: "wah-12", name: "Toe Board 150mm Minimum", type: "inspection_check", required: true, description: "Toe board minimum 150mm high at floor level" },
      { id: "wah-13", name: "No Gaps Greater Than 225mm", type: "inspection_check", required: true, description: "No gap between any edge protection elements exceeds 225mm" },
      { id: "wah-14", name: "Edge Protection Secure", type: "inspection_check", required: true, description: "All posts, rails, and connections secure and not loose" },
      { id: "wah-15", name: "All Penetrations Covered", type: "inspection_check", required: true, description: "Floor penetrations and voids covered with secured covers" },
    ],
  },
  {
    id: "sec-wah-3",
    name: "Harness & Fall Arrest Equipment",
    order: 2,
    description: "Personal fall arrest equipment inspection",
    allowRepeats: false,
    items: [
      { id: "wah-20", name: "Harness Within Inspection Date", type: "pass_fail_flag", required: true, description: "Harness has current inspection tag (within 6 months)" },
      { id: "wah-21", name: "Harness Webbing Condition", type: "pass_fail_flag", required: true, description: "No cuts, fraying, burns, or chemical damage to webbing" },
      { id: "wah-22", name: "Buckles & D-Rings Condition", type: "pass_fail_flag", required: true, description: "All buckles, D-rings, and hardware in good condition" },
      { id: "wah-23", name: "Lanyard / SRL Condition", type: "pass_fail_flag", required: true, description: "Lanyard or self-retracting lifeline in good condition" },
      { id: "wah-24", name: "Shock Absorber Not Deployed", type: "pass_fail_flag", required: true, description: "Energy absorber not previously activated (not stretched)" },
      { id: "wah-25", name: "Anchor Point Adequate", type: "pass_fail_flag", required: true, description: "Anchor point rated for required load (minimum 15kN or 12kN engineered)" },
      { id: "wah-26", name: "Fall Distance Clearance Adequate", type: "pass_fail_flag", required: true, description: "Sufficient clearance below for fall arrest to deploy before impact" },
      { id: "wah-27", name: "Rescue Plan in Place", type: "pass_fail_flag", required: true, description: "Plan to rescue a suspended worker within 5-10 minutes" },
    ],
  },
  {
    id: "sec-wah-4",
    name: "Worker Competency",
    order: 3,
    description: "Worker training and competency verification",
    allowRepeats: false,
    items: [
      { id: "wah-30", name: "Working at Heights Training Current", type: "pass_fail_flag", required: true, description: "Worker has completed working at heights training (within 2 years)" },
      { id: "wah-31", name: "Harness Fit Check Performed", type: "pass_fail_flag", required: true, description: "Worker has performed harness fit check and adjusted correctly" },
      { id: "wah-32", name: "Worker Fit for Duty", type: "pass_fail_flag", required: true, description: "Worker is physically fit, no fatigue, dizziness, or medication issues" },
      { id: "wah-33", name: "Buddy System in Place", type: "pass_fail_flag", required: true, description: "At least two workers present, buddy system for monitoring" },
    ],
  },
  {
    id: "sec-wah-5",
    name: "Sign-off",
    order: 4,
    description: "Approval to proceed with work at heights",
    allowRepeats: false,
    items: [
      { id: "wah-40", name: "All Controls in Place", type: "pass_fail_flag", required: true, description: "All identified controls implemented and verified" },
      { id: "wah-41", name: "Worker Signature", type: "signature_field", required: true, description: "Worker confirms understanding of all requirements" },
      { id: "wah-42", name: "Supervisor Signature", type: "signature_field", required: true, description: "Supervisor authorises work to proceed" },
    ],
  },
];

export const CONFINED_SPACE_SECTIONS = [
  {
    id: "sec-cs-1",
    name: "Entry Permit Details",
    order: 0,
    description: "Confined space identification and permit information",
    allowRepeats: false,
    items: [
      { id: "cs-1", name: "Permit Number", type: "text_field", required: true, placeholder: "Confined space entry permit number" },
      { id: "cs-2", name: "Date & Time of Entry", type: "datetime_field", required: true },
      { id: "cs-3", name: "Confined Space Location", type: "text_field", required: true, placeholder: "e.g. Basement sump pit, lift shaft, riser duct" },
      { id: "cs-4", name: "Confined Space Type", type: "dropdown", required: true, options: [{ text: "Tank / Vessel", value: "tank" }, { text: "Pit / Sump", value: "pit" }, { text: "Duct / Riser", value: "duct" }, { text: "Shaft / Tunnel", value: "shaft" }, { text: "Void / Ceiling Space", value: "void" }, { text: "Other Enclosed Space", value: "other" }] },
      { id: "cs-5", name: "Reason for Entry", type: "textarea", required: true, placeholder: "Describe work to be performed inside confined space" },
      { id: "cs-6", name: "Expected Duration of Entry", type: "text_field", required: true, placeholder: "e.g. 2 hours" },
      { id: "cs-7", name: "Entrant Name(s)", type: "textarea", required: true, placeholder: "Names of all persons entering the space" },
      { id: "cs-8", name: "Standby Person", type: "text_field", required: true, placeholder: "Name of person stationed outside the space" },
    ],
  },
  {
    id: "sec-cs-2",
    name: "Atmospheric Testing",
    order: 1,
    description: "Gas testing results before and during entry",
    allowRepeats: false,
    items: [
      { id: "cs-10", name: "Gas Detector Calibrated", type: "pass_fail_flag", required: true, description: "Gas detector bump-tested or calibrated before use" },
      { id: "cs-11", name: "Gas Detector Serial Number", type: "text_field", required: true, placeholder: "Detector serial/asset number" },
      { id: "cs-12", name: "Oxygen Level (%)", type: "number_field", required: true, placeholder: "Safe range: 19.5% - 23.5%", min: 0, max: 100 },
      { id: "cs-13", name: "Oxygen Level Acceptable (19.5-23.5%)", type: "pass_fail_flag", required: true },
      { id: "cs-14", name: "LEL / Flammable Gas (%)", type: "number_field", required: true, placeholder: "Must be below 5% LEL", min: 0, max: 100 },
      { id: "cs-15", name: "LEL Below 5%", type: "pass_fail_flag", required: true },
      { id: "cs-16", name: "H2S (ppm)", type: "number_field", required: true, placeholder: "Must be below 10ppm", min: 0 },
      { id: "cs-17", name: "CO (ppm)", type: "number_field", required: true, placeholder: "Must be below 30ppm", min: 0 },
      { id: "cs-18", name: "Continuous Monitoring in Place", type: "pass_fail_flag", required: true, description: "Personal gas monitor worn by entrant during entry" },
      { id: "cs-19", name: "Forced Ventilation Running", type: "yes_no_na", required: true, description: "Mechanical ventilation operating where required" },
    ],
  },
  {
    id: "sec-cs-3",
    name: "Pre-Entry Safety Checks",
    order: 2,
    description: "Safety controls verified before entry",
    allowRepeats: false,
    items: [
      { id: "cs-20", name: "All Pipes/Lines Isolated & Tagged", type: "pass_fail_flag", required: true, description: "All pipes, lines, and services isolated and lock-out/tag-out applied" },
      { id: "cs-21", name: "Electrical Isolation", type: "pass_fail_flag", required: true, description: "All electrical equipment in/near the space isolated" },
      { id: "cs-22", name: "Mechanical Isolation", type: "pass_fail_flag", required: true, description: "All mechanical equipment isolated (agitators, pumps, etc.)" },
      { id: "cs-23", name: "Entry/Exit Route Clear", type: "pass_fail_flag", required: true, description: "Entry and emergency exit routes clear and unobstructed" },
      { id: "cs-24", name: "Rescue Equipment Available", type: "pass_fail_flag", required: true, description: "Rescue tripod, winch, harness, and lifeline available" },
      { id: "cs-25", name: "Communication System Tested", type: "pass_fail_flag", required: true, description: "Communication between entrant and standby person verified" },
      { id: "cs-26", name: "Lighting Adequate", type: "pass_fail_flag", required: true, description: "Intrinsically safe lighting if flammable atmosphere possible" },
      { id: "cs-27", name: "First Aid Kit at Entry Point", type: "pass_fail_flag", required: true, description: "First aid kit and emergency equipment at entry point" },
    ],
  },
  {
    id: "sec-cs-4",
    name: "Entrant PPE",
    order: 3,
    description: "Personal protective equipment for confined space entry",
    allowRepeats: false,
    items: [
      { id: "cs-30", name: "Full Body Harness", type: "pass_fail_flag", required: true, description: "Full body harness fitted and connected to lifeline" },
      { id: "cs-31", name: "Respiratory Protection", type: "yes_no_na", required: true, description: "SCBA or airline respirator if atmosphere is or may become hazardous" },
      { id: "cs-32", name: "Personal Gas Monitor", type: "pass_fail_flag", required: true, description: "Personal 4-gas monitor worn by entrant" },
      { id: "cs-33", name: "Appropriate Clothing", type: "pass_fail_flag", required: true, description: "Non-synthetic, fire-resistant clothing if flammable risk" },
      { id: "cs-34", name: "Head Protection", type: "pass_fail_flag", required: true, description: "Hard hat or bump cap as appropriate" },
    ],
  },
  {
    id: "sec-cs-5",
    name: "Sign-off & Authorisation",
    order: 4,
    description: "Entry permit authorisation",
    allowRepeats: false,
    items: [
      { id: "cs-40", name: "Entry Approved", type: "pass_fail_flag", required: true, description: "All checks passed, entry authorised" },
      { id: "cs-41", name: "Entrant Signature", type: "signature_field", required: true, description: "Entrant confirms understanding of all hazards and controls" },
      { id: "cs-42", name: "Standby Person Signature", type: "signature_field", required: true, description: "Standby person confirms understanding of role and emergency procedures" },
      { id: "cs-43", name: "Permit Issuer Signature", type: "signature_field", required: true, description: "Permit issuer authorisation" },
      { id: "cs-44", name: "Entry Completion Time", type: "datetime_field", required: false, description: "Time all entrants exited and space secured" },
      { id: "cs-45", name: "Permit Closed Signature", type: "signature_field", required: false, description: "Confirmation that permit is closed and space secured" },
    ],
  },
];

export const EXCAVATION_SAFETY_SECTIONS = [
  {
    id: "sec-ex-1",
    name: "Excavation Details",
    order: 0,
    description: "Excavation location and scope",
    allowRepeats: false,
    items: [
      { id: "ex-1", name: "Excavation Location", type: "text_field", required: true, placeholder: "e.g. Gridline A-B, basement bulk excavation" },
      { id: "ex-2", name: "Date of Inspection", type: "date_field", required: true },
      { id: "ex-3", name: "Excavation Depth (metres)", type: "number_field", required: true, placeholder: "Maximum excavation depth" },
      { id: "ex-4", name: "Excavation Type", type: "dropdown", required: true, options: [{ text: "Open Cut / Bulk Excavation", value: "open_cut" }, { text: "Trench", value: "trench" }, { text: "Shaft / Pit", value: "shaft" }, { text: "Bored Pile", value: "bored_pile" }, { text: "Benched Excavation", value: "benched" }] },
      { id: "ex-5", name: "Soil Classification", type: "dropdown", required: true, options: [{ text: "Rock", value: "rock" }, { text: "Cohesive (Clay)", value: "clay" }, { text: "Non-Cohesive (Sand/Gravel)", value: "sand" }, { text: "Fill Material", value: "fill" }, { text: "Mixed / Unknown", value: "mixed" }] },
      { id: "ex-6", name: "Excavation Deeper than 1.5m", type: "yes_no_na", required: true, description: "Excavations over 1.5m require shoring/battering/benching" },
    ],
  },
  {
    id: "sec-ex-2",
    name: "Underground Services",
    order: 1,
    description: "Underground services identification and protection",
    allowRepeats: false,
    items: [
      { id: "ex-10", name: "Dial Before You Dig (DBYD) Obtained", type: "pass_fail_flag", required: true, description: "Current DBYD plans obtained for the excavation area" },
      { id: "ex-11", name: "Services Locator Scan Completed", type: "pass_fail_flag", required: true, description: "Ground penetrating radar / cable locator scan done" },
      { id: "ex-12", name: "Services Potholed & Marked", type: "pass_fail_flag", required: true, description: "Underground services hand-dug and physically identified" },
      { id: "ex-13", name: "Electrical Cables Identified", type: "yes_no_na", required: true, description: "Any underground electrical cables identified and marked" },
      { id: "ex-14", name: "Gas Lines Identified", type: "yes_no_na", required: true, description: "Any gas lines identified and marked" },
      { id: "ex-15", name: "Water/Sewer Identified", type: "yes_no_na", required: true, description: "Any water or sewer lines identified and marked" },
      { id: "ex-16", name: "Telco/Data Cables Identified", type: "yes_no_na", required: true, description: "Any telecommunications cables identified and marked" },
      { id: "ex-17", name: "Safe Dig Zone Established", type: "pass_fail_flag", required: true, description: "No machine digging within safe zone of services (hand dig only)" },
    ],
  },
  {
    id: "sec-ex-3",
    name: "Ground Support & Stability",
    order: 2,
    description: "Shoring, battering, and ground stability checks",
    allowRepeats: false,
    items: [
      { id: "ex-20", name: "Shoring / Battering System in Place", type: "pass_fail_flag", required: true, description: "Appropriate ground support system installed for depth" },
      { id: "ex-21", name: "Shoring Designed by Engineer", type: "yes_no_na", required: true, description: "Shoring system designed or approved by geotechnical engineer" },
      { id: "ex-22", name: "Batter Angle Appropriate", type: "yes_no_na", required: true, description: "Batter angle appropriate for soil type and conditions" },
      { id: "ex-23", name: "No Surcharge Loads Near Edge", type: "pass_fail_flag", required: true, description: "No heavy loads, plant, or spoil stored near excavation edge" },
      { id: "ex-24", name: "Dewatering System Working", type: "yes_no_na", required: true, description: "Water ingress being managed, pumps operational" },
      { id: "ex-25", name: "No Signs of Ground Movement", type: "pass_fail_flag", required: true, description: "No cracking, slumping, or subsidence around the excavation" },
      { id: "ex-26", name: "Adjacent Structures Monitored", type: "yes_no_na", required: true, description: "Survey monitoring of adjacent buildings/structures if required" },
    ],
  },
  {
    id: "sec-ex-4",
    name: "Excavation Safety Controls",
    order: 3,
    description: "Access, barricading, and safety controls",
    allowRepeats: false,
    items: [
      { id: "ex-30", name: "Barricading / Edge Protection", type: "pass_fail_flag", required: true, description: "Excavation edges barricaded with solid barriers (not tape)" },
      { id: "ex-31", name: "Safe Access/Egress (Ladder/Ramp)", type: "pass_fail_flag", required: true, description: "Safe entry/exit within 9m of any worker in excavation" },
      { id: "ex-32", name: "Signage Displayed", type: "pass_fail_flag", required: true, description: "Warning signs displayed around excavation perimeter" },
      { id: "ex-33", name: "Traffic Management in Place", type: "yes_no_na", required: true, description: "Vehicle movement controls around the excavation" },
      { id: "ex-34", name: "Spotter for Plant Operations", type: "yes_no_na", required: true, description: "Spotter assigned when plant operating near excavation edge" },
      { id: "ex-35", name: "Emergency Rescue Plan", type: "pass_fail_flag", required: true, description: "Rescue plan in place for worker recovery from excavation" },
    ],
  },
  {
    id: "sec-ex-5",
    name: "Sign-off",
    order: 4,
    description: "Inspection sign-off",
    allowRepeats: false,
    items: [
      { id: "ex-40", name: "Excavation Safe to Enter/Continue", type: "pass_fail_flag", required: true },
      { id: "ex-41", name: "Inspector Comments", type: "textarea", required: false, placeholder: "Additional observations or conditions" },
      { id: "ex-42", name: "Inspector Signature", type: "signature_field", required: true },
      { id: "ex-43", name: "Next Inspection Date", type: "date_field", required: false, description: "Schedule next inspection (daily for occupied excavations)" },
    ],
  },
];

export const SCAFFOLD_INSPECTION_SECTIONS = [
  {
    id: "sec-sc-1",
    name: "Scaffold Details",
    order: 0,
    description: "Scaffold identification and details",
    allowRepeats: false,
    items: [
      { id: "sc-1", name: "Scaffold Tag / ID Number", type: "text_field", required: true, placeholder: "Unique scaffold identification tag" },
      { id: "sc-2", name: "Scaffold Location", type: "text_field", required: true, placeholder: "e.g. North elevation, Level 3-6" },
      { id: "sc-3", name: "Scaffold Type", type: "dropdown", required: true, options: [{ text: "Tube & Coupler", value: "tube_coupler" }, { text: "Modular / System Scaffold", value: "modular" }, { text: "Mobile Scaffold / Tower", value: "mobile" }, { text: "Cantilever Scaffold", value: "cantilever" }, { text: "Suspended Scaffold", value: "suspended" }, { text: "Mast Climbing Work Platform", value: "mast_climbing" }] },
      { id: "sc-4", name: "Scaffold Height (metres)", type: "number_field", required: true },
      { id: "sc-5", name: "Scaffold Erector Company", type: "text_field", required: true, placeholder: "Name of scaffolding subcontractor" },
      { id: "sc-6", name: "Date of Inspection", type: "date_field", required: true },
      { id: "sc-7", name: "Inspection Type", type: "dropdown", required: true, options: [{ text: "Initial Erection Handover", value: "handover" }, { text: "Weekly Routine Inspection", value: "weekly" }, { text: "After Adverse Weather", value: "weather" }, { text: "After Modification", value: "modification" }, { text: "After Incident / Impact", value: "incident" }] },
    ],
  },
  {
    id: "sec-sc-2",
    name: "Structural Integrity",
    order: 1,
    description: "Structural components inspection",
    allowRepeats: false,
    items: [
      { id: "sc-10", name: "Base Plates / Sole Boards", type: "inspection_check", required: true, description: "Base plates level, on solid ground or sole boards, not on bricks" },
      { id: "sc-11", name: "Standards / Uprights Vertical", type: "inspection_check", required: true, description: "Vertical members plumb and in good condition" },
      { id: "sc-12", name: "Ledgers Level & Connected", type: "inspection_check", required: true, description: "Horizontal ledgers level and securely connected" },
      { id: "sc-13", name: "Bracing Installed Correctly", type: "inspection_check", required: true, description: "Diagonal bracing installed per design" },
      { id: "sc-14", name: "Ties / Anchors to Structure", type: "inspection_check", required: true, description: "Ties to building structure secure and at correct spacing" },
      { id: "sc-15", name: "No Damaged or Bent Components", type: "inspection_check", required: true, description: "No visibly damaged, corroded, or bent tubes/components" },
      { id: "sc-16", name: "Couplers Tight", type: "inspection_check", required: true, description: "All couplers and connections properly tightened" },
    ],
  },
  {
    id: "sec-sc-3",
    name: "Platforms & Access",
    order: 2,
    description: "Working platforms and access routes",
    allowRepeats: false,
    items: [
      { id: "sc-20", name: "Platform Boards Full Width", type: "inspection_check", required: true, description: "Working platforms fully boarded with no gaps >25mm" },
      { id: "sc-21", name: "Boards Secured / Tied Down", type: "inspection_check", required: true, description: "Platform boards secured and cannot be dislodged" },
      { id: "sc-22", name: "No Boards Damaged or Split", type: "inspection_check", required: true, description: "All boards in serviceable condition, no rot or splits" },
      { id: "sc-23", name: "Ladder Access Provided", type: "inspection_check", required: true, description: "Internal ladder access between levels, extending 1m above platform" },
      { id: "sc-24", name: "Access Gates Fitted", type: "inspection_check", required: true, description: "Self-closing gates at access points (not open sides)" },
      { id: "sc-25", name: "Guardrails at 950-1050mm", type: "inspection_check", required: true, description: "Top guardrails at correct height on all open sides" },
      { id: "sc-26", name: "Mid Rails Fitted", type: "inspection_check", required: true, description: "Mid rails installed on all open sides" },
      { id: "sc-27", name: "Toe Boards 150mm Minimum", type: "inspection_check", required: true, description: "Toe boards at least 150mm high on all working platforms" },
    ],
  },
  {
    id: "sec-sc-4",
    name: "Special Requirements",
    order: 3,
    description: "Additional checks for special scaffold types or conditions",
    allowRepeats: false,
    items: [
      { id: "sc-30", name: "Loading Signage Displayed", type: "inspection_check", required: true, description: "Maximum load capacity signs displayed on each level" },
      { id: "sc-31", name: "Containment Screens / Shade Cloth", type: "inspection_check", required: false, description: "If fitted, screens secure and not creating excessive wind load" },
      { id: "sc-32", name: "Overhead Protection", type: "inspection_check", required: false, description: "Overhead fans or catch platforms where required" },
      { id: "sc-33", name: "Scaffold Design Available", type: "yes_no_na", required: true, description: "Engineer's scaffold design drawings available on site" },
      { id: "sc-34", name: "Scaffold Not Overloaded", type: "inspection_check", required: true, description: "Materials stored on scaffold within rated capacity" },
      { id: "sc-35", name: "No Unauthorised Modifications", type: "inspection_check", required: true, description: "No components removed, added, or modified by non-scaffolders" },
    ],
  },
  {
    id: "sec-sc-5",
    name: "Tag & Sign-off",
    order: 4,
    description: "Scaffold tag status and inspection sign-off",
    allowRepeats: false,
    items: [
      { id: "sc-40", name: "Scaffold Tag Status", type: "dropdown", required: true, options: [{ text: "GREEN - Safe to Use", value: "green" }, { text: "YELLOW - Restricted Use (conditions apply)", value: "yellow" }, { text: "RED - Do Not Use (incomplete/unsafe)", value: "red" }] },
      { id: "sc-41", name: "Restrictions (if Yellow Tag)", type: "textarea", required: false, placeholder: "Describe any restrictions or conditions of use" },
      { id: "sc-42", name: "Defects Requiring Rectification", type: "textarea", required: false, placeholder: "List any defects that need to be fixed" },
      { id: "sc-43", name: "Inspector Name & Ticket Number", type: "text_field", required: true, placeholder: "Scaffolder/inspector name and licence number" },
      { id: "sc-44", name: "Inspector Signature", type: "signature_field", required: true, description: "Scaffold inspector sign-off" },
      { id: "sc-45", name: "Next Inspection Due", type: "date_field", required: true, description: "Date of next scheduled inspection (max 30 days)" },
    ],
  },
];

export const MOBILE_PLANT_PRESTART_SECTIONS = [
  {
    id: "sec-mp-1",
    name: "Plant Identification",
    order: 0,
    description: "Plant and operator details",
    allowRepeats: false,
    items: [
      { id: "mp-1", name: "Plant Type", type: "dropdown", required: true, options: [{ text: "Excavator", value: "excavator" }, { text: "Crane (Mobile)", value: "mobile_crane" }, { text: "Forklift", value: "forklift" }, { text: "Concrete Pump", value: "concrete_pump" }, { text: "Telehandler", value: "telehandler" }, { text: "Boom / Scissor Lift (EWP)", value: "ewp" }, { text: "Skid Steer / Bobcat", value: "skid_steer" }, { text: "Roller / Compactor", value: "roller" }, { text: "Truck (Rigid / Articulated)", value: "truck" }, { text: "Other", value: "other" }] },
      { id: "mp-2", name: "Plant ID / Rego Number", type: "text_field", required: true, placeholder: "Asset number or registration" },
      { id: "mp-3", name: "Make & Model", type: "text_field", required: true, placeholder: "e.g. CAT 320, Liebherr LTM 1060" },
      { id: "mp-4", name: "Operator Name", type: "text_field", required: true },
      { id: "mp-5", name: "Operator Licence / Ticket Number", type: "text_field", required: true, placeholder: "High risk work licence number" },
      { id: "mp-6", name: "Licence Sighted & Current", type: "pass_fail_flag", required: true, description: "Operator's licence sighted and within validity" },
      { id: "mp-7", name: "Date of Pre-Start", type: "date_field", required: true },
      { id: "mp-8", name: "Hour Meter Reading", type: "number_field", required: false, placeholder: "Current hour meter reading" },
    ],
  },
  {
    id: "sec-mp-2",
    name: "Safety Equipment",
    order: 1,
    description: "Safety systems and emergency equipment",
    allowRepeats: false,
    items: [
      { id: "mp-10", name: "Seatbelt / Operator Restraint", type: "inspection_check", required: true, description: "Seatbelt present and functional" },
      { id: "mp-11", name: "ROPS / FOPS Intact", type: "inspection_check", required: true, description: "Roll-over / Falling object protection structure undamaged" },
      { id: "mp-12", name: "Reverse Alarm / Buzzer", type: "inspection_check", required: true, description: "Reversing alarm functioning" },
      { id: "mp-13", name: "Flashing Beacon / Strobe", type: "inspection_check", required: true, description: "Warning beacon operational" },
      { id: "mp-14", name: "Fire Extinguisher", type: "inspection_check", required: true, description: "Fire extinguisher charged and accessible" },
      { id: "mp-15", name: "First Aid Kit", type: "inspection_check", required: false, description: "First aid kit stocked and accessible" },
      { id: "mp-16", name: "Mirrors / Camera System", type: "inspection_check", required: true, description: "All mirrors clean and camera system working" },
      { id: "mp-17", name: "Horn", type: "inspection_check", required: true, description: "Horn functioning" },
      { id: "mp-18", name: "Emergency Stop (E-Stop)", type: "inspection_check", required: true, description: "Emergency stop button/s functional" },
    ],
  },
  {
    id: "sec-mp-3",
    name: "Mechanical Checks",
    order: 2,
    description: "Mechanical systems and fluid levels",
    allowRepeats: false,
    items: [
      { id: "mp-20", name: "Engine Oil Level", type: "inspection_check", required: true, description: "Engine oil at correct level, no leaks" },
      { id: "mp-21", name: "Coolant Level", type: "inspection_check", required: true, description: "Coolant at correct level, no leaks" },
      { id: "mp-22", name: "Hydraulic Fluid Level", type: "inspection_check", required: true, description: "Hydraulic oil at correct level, no visible leaks" },
      { id: "mp-23", name: "Fuel Level Adequate", type: "inspection_check", required: true, description: "Sufficient fuel for planned operations" },
      { id: "mp-24", name: "Tyres / Tracks Condition", type: "inspection_check", required: true, description: "Tyres inflated correctly, tracks tensioned, no damage" },
      { id: "mp-25", name: "Brakes Functional", type: "inspection_check", required: true, description: "Service and park brakes operating correctly" },
      { id: "mp-26", name: "Lights & Indicators", type: "inspection_check", required: true, description: "Headlights, tail lights, and indicators all working" },
      { id: "mp-27", name: "No Fluid Leaks Visible", type: "inspection_check", required: true, description: "No oil, hydraulic, or coolant leaks under or around plant" },
      { id: "mp-28", name: "Windscreen & Wipers", type: "inspection_check", required: false, description: "Windscreen clean, no cracks, wipers functional" },
    ],
  },
  {
    id: "sec-mp-4",
    name: "Operational Checks",
    order: 3,
    description: "Operational functionality checks",
    allowRepeats: false,
    items: [
      { id: "mp-30", name: "All Controls Functioning", type: "inspection_check", required: true, description: "Joysticks, levers, pedals, and controls responsive" },
      { id: "mp-31", name: "Boom / Arm Movement Smooth", type: "inspection_check", required: false, description: "Boom and arm movements smooth, no jerking or drift" },
      { id: "mp-32", name: "Slew Ring Operation", type: "inspection_check", required: false, description: "Slew operation smooth, no unusual noises" },
      { id: "mp-33", name: "Load Chart Available", type: "inspection_check", required: false, description: "Load chart visible and legible in the cab" },
      { id: "mp-34", name: "LMI / Load Indicator Working", type: "inspection_check", required: false, description: "Load moment indicator functioning correctly" },
      { id: "mp-35", name: "Cabin Clean & Uncluttered", type: "inspection_check", required: true, description: "Cab clean, no loose items, clear visibility" },
      { id: "mp-36", name: "Ground Conditions Suitable", type: "inspection_check", required: true, description: "Ground firm enough for safe operation" },
    ],
  },
  {
    id: "sec-mp-5",
    name: "Pre-Start Result",
    order: 4,
    description: "Overall pre-start assessment",
    allowRepeats: false,
    items: [
      { id: "mp-40", name: "Defects Found", type: "textarea", required: false, placeholder: "Describe any defects or issues found during pre-start" },
      { id: "mp-41", name: "Defect Photos", type: "multi_photo", required: false, description: "Photograph any defects found" },
      { id: "mp-42", name: "Plant Fit for Use", type: "pass_fail_flag", required: true, description: "Overall assessment - plant safe to operate?" },
      { id: "mp-43", name: "Operator Signature", type: "signature_field", required: true, description: "Operator confirms pre-start completed" },
    ],
  },
];

export const CONCRETE_POUR_PERMIT_SECTIONS = [
  {
    id: "sec-cp-1",
    name: "Pour Details",
    order: 0,
    description: "Concrete pour identification and specification",
    allowRepeats: false,
    items: [
      { id: "cp-1", name: "Pour Location", type: "text_field", required: true, placeholder: "e.g. Level 8 slab, Gridline A-F / 1-6" },
      { id: "cp-2", name: "Pour Date & Start Time", type: "datetime_field", required: true },
      { id: "cp-3", name: "Element Type", type: "dropdown", required: true, options: [{ text: "Suspended Slab", value: "slab" }, { text: "Ground Slab / Raft", value: "ground_slab" }, { text: "Columns", value: "columns" }, { text: "Walls / Core", value: "walls" }, { text: "Beams", value: "beams" }, { text: "Footings / Piles", value: "footings" }, { text: "Transfer Structure", value: "transfer" }] },
      { id: "cp-4", name: "Estimated Volume (m³)", type: "number_field", required: true, placeholder: "Estimated concrete volume" },
      { id: "cp-5", name: "Concrete Grade", type: "text_field", required: true, placeholder: "e.g. N32/20, N40/10" },
      { id: "cp-6", name: "Slump (mm)", type: "number_field", required: true, placeholder: "Specified slump" },
      { id: "cp-7", name: "Concrete Supplier", type: "text_field", required: true, placeholder: "Ready-mix supplier name" },
      { id: "cp-8", name: "Pump Operator / Company", type: "text_field", required: false, placeholder: "Concrete pump operator if used" },
    ],
  },
  {
    id: "sec-cp-2",
    name: "Pre-Pour Inspection",
    order: 1,
    description: "Structural and formwork checks before pour",
    allowRepeats: false,
    items: [
      { id: "cp-10", name: "Formwork / Shutters Complete", type: "pass_fail_flag", required: true, description: "All formwork erected, complete, and sealed" },
      { id: "cp-11", name: "Reinforcement Approved", type: "pass_fail_flag", required: true, description: "Steel reinforcement inspected and approved by engineer/inspector" },
      { id: "cp-12", name: "Hold Points Signed Off", type: "pass_fail_flag", required: true, description: "All engineering hold points released" },
      { id: "cp-13", name: "Embeds & Cast-Ins Positioned", type: "pass_fail_flag", required: true, description: "All cast-in items (ferrules, plates, sleeves) positioned" },
      { id: "cp-14", name: "Services Sleeved / Protected", type: "pass_fail_flag", required: true, description: "Electrical conduits, plumbing sleeves, and penetrations set" },
      { id: "cp-15", name: "Pour Joints / Stop Ends Set", type: "pass_fail_flag", required: true, description: "Construction joints and stop ends correctly positioned" },
      { id: "cp-16", name: "Formwork Props / Backpropping", type: "pass_fail_flag", required: true, description: "Props and backpropping installed per engineer requirements" },
    ],
  },
  {
    id: "sec-cp-3",
    name: "Safety Checks",
    order: 2,
    description: "Safety controls for the pour operation",
    allowRepeats: false,
    items: [
      { id: "cp-20", name: "Edge Protection in Place", type: "pass_fail_flag", required: true, description: "Guardrails and edge protection around pour area" },
      { id: "cp-21", name: "Penetrations Covered Until Pour", type: "pass_fail_flag", required: true, description: "All penetrations covered or barricaded" },
      { id: "cp-22", name: "Pump Line Secured", type: "yes_no_na", required: true, description: "Concrete pump line secured and restrained" },
      { id: "cp-23", name: "Traffic Management for Trucks", type: "pass_fail_flag", required: true, description: "Truck route, wash-out area, and traffic management in place" },
      { id: "cp-24", name: "Drop Zone for Crane Skip", type: "yes_no_na", required: true, description: "If crane-skip pour, drop zone established" },
      { id: "cp-25", name: "Weather Forecast Checked", type: "pass_fail_flag", required: true, description: "No adverse weather expected during pour window" },
      { id: "cp-26", name: "Wet Weather Plan", type: "yes_no_na", required: true, description: "Contingency plan for unexpected rain (covers/tarps available)" },
      { id: "cp-27", name: "Communication Plan", type: "pass_fail_flag", required: true, description: "Communication established between pump operator, finishers, and supervisor" },
    ],
  },
  {
    id: "sec-cp-4",
    name: "Pour Authorisation",
    order: 3,
    description: "Pour permit sign-off",
    allowRepeats: false,
    items: [
      { id: "cp-30", name: "Pour Approved to Proceed", type: "pass_fail_flag", required: true },
      { id: "cp-31", name: "Engineer / Inspector Name", type: "text_field", required: true },
      { id: "cp-32", name: "Engineer / Inspector Signature", type: "signature_field", required: true },
      { id: "cp-33", name: "Site Foreman Signature", type: "signature_field", required: true },
    ],
  },
];

export const TOOLBOX_TALK_SECTIONS = [
  {
    id: "sec-tt-1",
    name: "Meeting Details",
    order: 0,
    description: "Toolbox talk details and attendees",
    allowRepeats: false,
    items: [
      { id: "tt-1", name: "Date & Time", type: "datetime_field", required: true },
      { id: "tt-2", name: "Location", type: "text_field", required: true, placeholder: "Where the toolbox talk was held" },
      { id: "tt-3", name: "Presenter / Supervisor", type: "staff_assignment", required: true },
      { id: "tt-4", name: "Company / Trade", type: "text_field", required: true, placeholder: "Which company or trade group" },
    ],
  },
  {
    id: "sec-tt-2",
    name: "Topics Covered",
    order: 1,
    description: "Safety topics discussed",
    allowRepeats: false,
    items: [
      { id: "tt-10", name: "Today's Work Activities", type: "textarea", required: true, placeholder: "Describe the work activities planned for today" },
      { id: "tt-11", name: "Key Hazards Identified", type: "textarea", required: true, placeholder: "List the main hazards associated with today's work" },
      { id: "tt-12", name: "Control Measures", type: "textarea", required: true, placeholder: "What controls are in place to manage these hazards?" },
      { id: "tt-13", name: "SWMS / JSA Reviewed", type: "pass_fail_flag", required: true, description: "Relevant Safe Work Method Statements reviewed with workers" },
      { id: "tt-14", name: "Permits Required", type: "textarea", required: false, placeholder: "List any permits needed (hot works, confined space, etc.)" },
      { id: "tt-15", name: "Environmental Conditions", type: "textarea", required: false, placeholder: "Weather, noise, dust, or other environmental factors" },
      { id: "tt-16", name: "Previous Incidents / Lessons Learnt", type: "textarea", required: false, placeholder: "Relevant incidents or safety alerts to share" },
      { id: "tt-17", name: "Crane Lifts / Critical Activities", type: "textarea", required: false, placeholder: "Any crane lifts or critical activities planned today" },
    ],
  },
  {
    id: "sec-tt-3",
    name: "Worker Acknowledgement",
    order: 2,
    description: "Attendees acknowledge understanding",
    allowRepeats: true,
    items: [
      { id: "tt-20", name: "Worker Name", type: "text_field", required: true },
      { id: "tt-21", name: "Worker Company", type: "text_field", required: true },
      { id: "tt-22", name: "Worker Signature", type: "signature_field", required: true, description: "Worker confirms attendance and understanding" },
    ],
  },
  {
    id: "sec-tt-4",
    name: "Actions & Close-out",
    order: 3,
    description: "Actions arising and presenter sign-off",
    allowRepeats: false,
    items: [
      { id: "tt-30", name: "Actions Arising", type: "textarea", required: false, placeholder: "Any actions or follow-ups from the toolbox talk" },
      { id: "tt-31", name: "Worker Concerns Raised", type: "textarea", required: false, placeholder: "Record any safety concerns raised by workers" },
      { id: "tt-32", name: "Presenter Signature", type: "signature_field", required: true, description: "Presenter confirms toolbox talk delivered" },
    ],
  },
];

export const SAFETY_TEMPLATE_DEFINITIONS = [
  {
    name: "Site Induction Checklist",
    code: "SITE_INDUCTION",
    description: "Comprehensive site-specific safety induction for all workers entering the site for the first time. Covers PPE requirements, emergency procedures, site rules, and high-rise specific hazards.",
    sections: SITE_INDUCTION_SECTIONS,
  },
  {
    name: "Safety Walk / Site Inspection",
    code: "SAFETY_WALK",
    description: "Structured safety walk inspection covering housekeeping, PPE compliance, fall prevention, plant safety, and hazardous materials. Includes repeatable observation logging with risk ratings and corrective actions.",
    sections: SAFETY_WALK_SECTIONS,
  },
  {
    name: "Drop Zone Checklist",
    code: "DROP_ZONE",
    description: "Drop zone establishment and verification checklist for overhead works including crane operations, formwork stripping, façade installation, and scaffold erection. Covers barricading, signage, overhead protection, and communication protocols.",
    sections: DROP_ZONE_SECTIONS,
  },
  {
    name: "Tower Crane Jump Safety Checklist",
    code: "CRANE_JUMP",
    description: "Comprehensive safety checklist for tower crane climbing/jumping operations. Covers pre-jump engineering reviews, weather checks, crew qualifications, during-jump monitoring, post-jump verification, and return-to-service approval.",
    sections: CRANE_JUMP_SECTIONS,
  },
  {
    name: "Hot Works Permit",
    code: "HOT_WORKS",
    description: "Hot works permit checklist for welding, cutting, grinding, and other heat-producing works. Includes fire prevention checks, PPE verification, post-work fire watch requirements, and permit authorisation.",
    sections: HOT_WORKS_SECTIONS,
  },
  {
    name: "Working at Heights Checklist",
    code: "WORKING_AT_HEIGHTS",
    description: "Working at heights safety checklist covering edge protection, harness inspection, fall arrest equipment checks, anchor point verification, fall clearance calculations, and worker competency verification.",
    sections: WORKING_AT_HEIGHTS_SECTIONS,
  },
  {
    name: "Confined Space Entry Permit",
    code: "CONFINED_SPACE",
    description: "Confined space entry permit and checklist covering atmospheric testing (O2, LEL, H2S, CO), isolation procedures, rescue equipment, ventilation, PPE, and multi-party sign-off.",
    sections: CONFINED_SPACE_SECTIONS,
  },
  {
    name: "Excavation Safety Inspection",
    code: "EXCAVATION",
    description: "Excavation safety inspection covering underground services identification (DBYD), shoring and ground stability, access/egress, barricading, traffic management, and geotechnical monitoring.",
    sections: EXCAVATION_SAFETY_SECTIONS,
  },
  {
    name: "Scaffold Inspection Checklist",
    code: "SCAFFOLD",
    description: "Scaffold inspection checklist for all scaffold types including structural integrity, platform completeness, guardrails, access, ties to structure, and scaffold tag (green/yellow/red) assignment.",
    sections: SCAFFOLD_INSPECTION_SECTIONS,
  },
  {
    name: "Mobile Plant Pre-Start Checklist",
    code: "PLANT_PRESTART",
    description: "Daily pre-start inspection for mobile plant and equipment including excavators, cranes, forklifts, EWPs, and trucks. Covers safety systems, mechanical checks, operational functionality, and operator licence verification.",
    sections: MOBILE_PLANT_PRESTART_SECTIONS,
  },
  {
    name: "Concrete Pour Permit",
    code: "CONCRETE_POUR",
    description: "Pre-pour permit checklist covering formwork completion, reinforcement approval, hold point sign-offs, cast-in items, safety controls (edge protection, drop zones), weather checks, and pour authorisation.",
    sections: CONCRETE_POUR_PERMIT_SECTIONS,
  },
  {
    name: "Toolbox Talk / Pre-Start Meeting",
    code: "TOOLBOX_TALK",
    description: "Daily toolbox talk and pre-start meeting record. Covers work activities, hazard identification, control measures, SWMS review, permits, and repeatable worker attendance/signature log.",
    sections: TOOLBOX_TALK_SECTIONS,
  },
];
