import { db } from "./db";
import { helpEntries } from "@shared/schema";
import { eq } from "drizzle-orm";

interface HelpSeed {
  key: string;
  scope: "PAGE" | "FIELD" | "ACTION" | "COLUMN" | "ERROR" | "GENERAL";
  title: string;
  shortText: string;
  bodyMd: string;
  keywords: string[];
  category: string;
  pageRoute?: string;
}

const pageHelp: HelpSeed[] = [
  {
    key: "page.dashboard",
    scope: "PAGE",
    title: "Dashboard",
    shortText: "Your personal overview of time tracking, tasks, and recent activity.",
    bodyMd: `## Dashboard Overview\n\nThe Dashboard gives you a quick snapshot of your day and outstanding items.\n\n### What you'll see\n- **Today's Hours** - Total time logged today\n- **Pending Days** - Days with unsubmitted timesheets\n- **Submitted Awaiting Approval** - Timesheets waiting for manager review\n- **Recent Logs** - Your most recent daily log entries\n- **Active Tasks** - Tasks assigned to you\n- **Unread Messages** - Recent chat messages\n\n### Tips\n- Click any card to navigate to the full page\n- Time tracking updates automatically as you log hours`,
    keywords: ["home", "overview", "stats", "time tracking"],
    category: "Dashboard",
    pageRoute: "/dashboard",
  },
  {
    key: "page.tasks",
    scope: "PAGE",
    title: "Tasks",
    shortText: "View and manage your tasks, create new ones, and track progress.",
    bodyMd: `## Tasks\n\nThe Tasks page is your central hub for work management.\n\n### Features\n- **Create tasks** with titles, descriptions, priorities, and due dates\n- **Assign tasks** to team members\n- **Track progress** with status updates\n- **Comment** on tasks for collaboration\n- **Filter and search** to find specific tasks\n\n### Task Statuses\n- **Open** - New or unstarted tasks\n- **In Progress** - Currently being worked on\n- **Completed** - Finished tasks\n- **Closed** - Archived tasks`,
    keywords: ["tasks", "todo", "work", "assign", "priority"],
    category: "Tasks",
    pageRoute: "/tasks",
  },
  {
    key: "page.chat",
    scope: "PAGE",
    title: "Chat",
    shortText: "Team messaging with direct messages, groups, and channels.",
    bodyMd: `## Chat\n\nReal-time messaging system for team communication.\n\n### Features\n- **Direct Messages** - Private 1-on-1 conversations\n- **Group Chats** - Multi-person conversations\n- **Channels** - Topic-based team discussions\n- **@Mentions** - Tag specific team members\n- **File Attachments** - Share files in conversations\n- **Notifications** - Stay updated on new messages`,
    keywords: ["chat", "messaging", "communication", "team"],
    category: "Chat",
    pageRoute: "/chat",
  },
  {
    key: "page.jobs",
    scope: "PAGE",
    title: "Jobs Management",
    shortText: "Manage all jobs from opportunity through to completion.",
    bodyMd: `## Jobs Management\n\nCentral hub for managing all construction jobs and projects.\n\n### Job Lifecycle\nJobs progress through phases:\n1. **Opportunity** - Initial lead or prospect\n2. **Quoting** - Preparing and submitting quotes\n3. **Won Awaiting Contract** - Quote accepted, contract pending\n4. **Contracted** - Active contract in place\n\n### Job Statuses\n- **Active** - Currently in progress\n- **On Hold** - Temporarily paused\n- **Pending Start** - Awaiting commencement\n- **Started** - Work has begun\n- **Completed** - Job finished\n- **Archived** - Filed away\n\n### Key Features\n- Create and edit job details\n- Track phase progression\n- View audit history of changes\n- Import panel estimates`,
    keywords: ["jobs", "projects", "contracts", "phases", "status"],
    category: "Jobs",
    pageRoute: "/admin/jobs",
  },
  {
    key: "page.panels",
    scope: "PAGE",
    title: "Panel Register",
    shortText: "View and manage all panels across jobs with lifecycle tracking.",
    bodyMd: `## Panel Register\n\nThe Panel Register provides a comprehensive view of all panels in the system.\n\n### Panel Lifecycle\nPanels progress through 14 stages from registration to delivery:\n- Registered, Drafted, Checked, Approved, Scheduled, and more\n\n### Features\n- Filter by job, status, level, and type\n- View panel specifications and dimensions\n- Track production progress\n- Access detailed panel information`,
    keywords: ["panels", "precast", "concrete", "production", "lifecycle"],
    category: "Panels",
    pageRoute: "/admin/panels",
  },
  {
    key: "page.documents",
    scope: "PAGE",
    title: "Document Register",
    shortText: "Manage project documents with version control and bundles.",
    bodyMd: `## Document Register\n\nCentralized document management system with version tracking.\n\n### Features\n- Upload and organize documents by job and category\n- **Version Control** - Track document revisions (Draft, IFA, IFC, Approved)\n- **Document Bundles** - Group related documents together\n- **QR Codes** - Generate shareable QR codes for bundles\n- **Entity Linking** - Link documents to jobs, panels, or other records`,
    keywords: ["documents", "files", "version control", "bundles"],
    category: "Documents",
    pageRoute: "/documents",
  },
  {
    key: "page.checklists",
    scope: "PAGE",
    title: "Checklists",
    shortText: "Complete quality and safety checklists for jobs and panels.",
    bodyMd: `## Checklists\n\nDigital checklist system for quality inspections and safety checks.\n\n### Features\n- Pre-Pour and Post-Pour quality inspections\n- Customizable templates with conditional fields\n- Photo evidence capture\n- Linked to specific panels and jobs\n- Completion tracking and reporting`,
    keywords: ["checklists", "quality", "inspection", "safety"],
    category: "Checklists",
    pageRoute: "/checklists",
  },
  {
    key: "page.logistics",
    scope: "PAGE",
    title: "Logistics",
    shortText: "Manage load lists, deliveries, and transport scheduling.",
    bodyMd: `## Logistics\n\nPlan and track panel deliveries from factory to site.\n\n### Features\n- **Load Lists** - Create and manage panel loading sequences\n- **Delivery Recording** - Log delivery details and confirmation\n- **Return Loads** - Track returned panels\n- **Transport Planning** - Schedule deliveries`,
    keywords: ["logistics", "delivery", "transport", "load lists", "trucks"],
    category: "Logistics",
    pageRoute: "/logistics",
  },
  {
    key: "page.production-slots",
    scope: "PAGE",
    title: "Production Slots",
    shortText: "Schedule and manage factory production slots for panel casting.",
    bodyMd: `## Production Slots\n\nSchedule panel production across factory beds.\n\n### Features\n- View production calendar by factory\n- Assign panels to production slots\n- Track slot status (Scheduled, Booked, Completed)\n- Multi-factory support`,
    keywords: ["production", "slots", "scheduling", "factory", "casting"],
    category: "Production",
    pageRoute: "/production-slots",
  },
  {
    key: "page.production-schedule",
    scope: "PAGE",
    title: "Production Schedule",
    shortText: "Overview of production timeline and panel manufacturing progress.",
    bodyMd: `## Production Schedule\n\nVisualize and manage the overall production timeline.\n\n### Features\n- Calendar view of production activities\n- Track manufacturing progress\n- View capacity utilization\n- Multi-factory scheduling`,
    keywords: ["production", "schedule", "timeline", "manufacturing"],
    category: "Production",
    pageRoute: "/production-schedule",
  },
  {
    key: "page.drafting-program",
    scope: "PAGE",
    title: "Drafting Program",
    shortText: "Track drafting progress and time allocation across jobs.",
    bodyMd: `## Drafting Program\n\nMonitor and manage the drafting workflow for panel designs.\n\n### Features\n- View drafting status by job\n- Track time spent on CAD and Revit work\n- Monitor drafting milestones\n- Allocate resources across projects`,
    keywords: ["drafting", "CAD", "Revit", "design", "drawings"],
    category: "Production",
    pageRoute: "/drafting-program",
  },
  {
    key: "page.procurement-reo",
    scope: "PAGE",
    title: "Reo Scheduling",
    shortText: "Manage reinforcement steel procurement and scheduling.",
    bodyMd: `## Reo Scheduling\n\nSchedule and track reinforcement steel orders for panel production.\n\n### Features\n- Link reo orders to production slots\n- Track order status and deliveries\n- Manage supplier relationships\n- Coordinate with production timeline`,
    keywords: ["reo", "reinforcement", "steel", "procurement", "scheduling"],
    category: "Production",
    pageRoute: "/procurement-reo",
  },
  {
    key: "page.daily-reports",
    scope: "PAGE",
    title: "Drafting Register",
    shortText: "Submit and review daily time logs for drafting activities.",
    bodyMd: `## Drafting Register\n\nDaily time logging system for tracking drafting hours.\n\n### Features\n- Log time against specific jobs and tasks\n- Submit daily timesheets for approval\n- View historical time entries\n- Track productive vs idle time`,
    keywords: ["daily", "time", "log", "timesheet", "hours"],
    category: "Time Management",
    pageRoute: "/daily-reports",
  },
  {
    key: "page.manual-entry",
    scope: "PAGE",
    title: "Manual Time Entry",
    shortText: "Manually enter time for past days or make corrections.",
    bodyMd: `## Manual Time Entry\n\nAdd or correct time entries for any date.\n\n### When to use\n- Forgot to log time on a specific day\n- Need to make corrections to existing entries\n- Adding time for activities not captured by the timer`,
    keywords: ["manual", "time", "entry", "correction"],
    category: "Time Management",
    pageRoute: "/manual-entry",
  },
  {
    key: "page.weekly-job-logs",
    scope: "PAGE",
    title: "Weekly Job Logs",
    shortText: "Weekly summary reports for job progress and activity.",
    bodyMd: `## Weekly Job Logs\n\nGenerate and review weekly summaries of job activity.\n\n### Features\n- Aggregate time data by job and week\n- Include EOT (Extension of Time) claims\n- Track weekly milestones and achievements\n- Export reports for stakeholders`,
    keywords: ["weekly", "report", "summary", "job logs"],
    category: "Reports",
    pageRoute: "/weekly-job-logs",
  },
  {
    key: "page.purchase-orders",
    scope: "PAGE",
    title: "Purchase Orders",
    shortText: "Create and manage purchase orders with customizable terms.",
    bodyMd: `## Purchase Orders\n\nFull purchase order management with rich text terms and conditions.\n\n### Features\n- Create POs linked to jobs and suppliers\n- Customizable terms and conditions with rich text editing\n- Track PO status and approvals\n- Receive goods against POs\n- Line item management with quantities and pricing`,
    keywords: ["purchase orders", "PO", "procurement", "buying"],
    category: "Finance",
    pageRoute: "/purchase-orders",
  },
  {
    key: "page.sales-pipeline",
    scope: "PAGE",
    title: "Sales Pipeline",
    shortText: "Track sales opportunities from lead to won or lost.",
    bodyMd: `## Sales Pipeline\n\nVisual pipeline for managing pre-sales opportunities.\n\n### Features\n- Kanban-style pipeline view\n- Track opportunity value and probability\n- Log sales activities and follow-ups\n- Convert opportunities to jobs\n- Filter by status, type, and date range`,
    keywords: ["sales", "pipeline", "opportunities", "leads", "CRM"],
    category: "Sales",
    pageRoute: "/sales-pipeline",
  },
  {
    key: "page.contracts",
    scope: "PAGE",
    title: "Contract Hub",
    shortText: "Manage job contracts, retention tracking, and contract details.",
    bodyMd: `## Contract Hub\n\nCentralized contract management for all jobs.\n\n### Features\n- View and edit contract details\n- Track contract retention amounts\n- Monitor contract milestones\n- Link to progress claims`,
    keywords: ["contracts", "retention", "agreement", "terms"],
    category: "Finance",
    pageRoute: "/contracts",
  },
  {
    key: "page.progress-claims",
    scope: "PAGE",
    title: "Progress Claims",
    shortText: "Submit and track progress payment claims for jobs.",
    bodyMd: `## Progress Claims\n\nManage progress payment claims throughout the job lifecycle.\n\n### Features\n- Create new progress claims\n- Track claim status and approvals\n- Automatic retention calculations\n- View retention reports\n- Link to contract details`,
    keywords: ["progress claims", "payments", "billing", "retention"],
    category: "Finance",
    pageRoute: "/progress-claims",
  },
  {
    key: "page.broadcast",
    scope: "PAGE",
    title: "Broadcast Messages",
    shortText: "Send broadcast messages to teams via SMS, WhatsApp, or email.",
    bodyMd: `## Broadcast Messages\n\nSend important announcements to your team through multiple channels.\n\n### Features\n- SMS broadcast messaging\n- WhatsApp message delivery\n- Email notifications\n- Target specific groups or all users`,
    keywords: ["broadcast", "messaging", "SMS", "WhatsApp", "announcements"],
    category: "Communication",
    pageRoute: "/broadcast",
  },
  {
    key: "page.kpi-dashboard",
    scope: "PAGE",
    title: "KPI Dashboard",
    shortText: "Key performance indicators and analytics for management oversight.",
    bodyMd: `## KPI Dashboard\n\nComprehensive analytics dashboard for performance monitoring.\n\n### Metrics Tracked\n- Production efficiency and output\n- Delivery performance\n- Time utilization rates\n- Financial summaries\n- Team productivity\n\n### Features\n- Interactive charts and graphs\n- Date range filtering\n- PDF export for presentations\n- Drill-down capability`,
    keywords: ["KPI", "analytics", "performance", "metrics", "dashboard"],
    category: "Reports",
    pageRoute: "/kpi-dashboard",
  },
  {
    key: "page.manager-review",
    scope: "PAGE",
    title: "Manager Review",
    shortText: "Review and approve submitted timesheets and daily logs.",
    bodyMd: `## Manager Review\n\nApprove or reject team member timesheets and daily logs.\n\n### Workflow\n1. Team members submit daily logs\n2. Logs appear in your review queue\n3. Review hours, activities, and notes\n4. Approve or reject with feedback`,
    keywords: ["review", "approval", "manager", "timesheet"],
    category: "Time Management",
    pageRoute: "/manager/review",
  },
  {
    key: "page.production-report",
    scope: "PAGE",
    title: "Production Report",
    shortText: "Detailed production performance reports and analysis.",
    bodyMd: `## Production Report\n\nAnalyze production output and efficiency.\n\n### Features\n- Daily production summaries\n- Panel completion tracking\n- Factory utilization metrics\n- Comparison across time periods`,
    keywords: ["production", "report", "analysis", "output"],
    category: "Reports",
    pageRoute: "/production-report",
  },
  {
    key: "page.checklist-reports",
    scope: "PAGE",
    title: "Checklist Reports",
    shortText: "View completion statistics and trends for quality checklists.",
    bodyMd: `## Checklist Reports\n\nTrack checklist completion rates and quality trends.\n\n### Features\n- Completion rate statistics\n- Filter by job, template, and date\n- Identify outstanding inspections\n- Track quality trends over time`,
    keywords: ["checklist", "reports", "quality", "statistics"],
    category: "Reports",
    pageRoute: "/checklist-reports",
  },
  {
    key: "page.reports",
    scope: "PAGE",
    title: "Reports",
    shortText: "General reporting tools and data exports.",
    bodyMd: `## Reports\n\nAccess various system reports and data exports.\n\n### Available Reports\n- Time tracking summaries\n- Job performance reports\n- Export data to CSV/PDF`,
    keywords: ["reports", "export", "data", "analysis"],
    category: "Reports",
    pageRoute: "/reports",
  },
  {
    key: "page.weekly-wages",
    scope: "PAGE",
    title: "Weekly Wages",
    shortText: "Weekly wage calculation and reporting for team members.",
    bodyMd: `## Weekly Wages\n\nCalculate and review weekly wages based on time logs.\n\n### Features\n- Automatic wage calculations\n- Overtime tracking\n- Export for payroll processing`,
    keywords: ["wages", "payroll", "salary", "weekly"],
    category: "Finance",
    pageRoute: "/weekly-wages",
  },
  {
    key: "page.downloads",
    scope: "PAGE",
    title: "Downloads",
    shortText: "Download exported files and generated reports.",
    bodyMd: `## Downloads\n\nAccess your generated reports and exported files.\n\n### Features\n- View recent downloads\n- Re-download previously generated files\n- Export data in various formats`,
    keywords: ["downloads", "export", "files"],
    category: "General",
    pageRoute: "/downloads",
  },
  {
    key: "page.admin.settings",
    scope: "PAGE",
    title: "Admin Settings",
    shortText: "Configure system-wide settings and preferences.",
    bodyMd: `## Admin Settings\n\nManage global system configuration.\n\n### Available Settings\n- Company branding and logo\n- Configurable rates\n- System preferences\n- Email and notification settings`,
    keywords: ["settings", "configuration", "admin", "preferences"],
    category: "Admin",
    pageRoute: "/admin/settings",
  },
  {
    key: "page.admin.users",
    scope: "PAGE",
    title: "User Management",
    shortText: "Add, edit, and manage user accounts and roles.",
    bodyMd: `## User Management\n\nManage system users and their access.\n\n### Features\n- Create new user accounts\n- Assign roles (User, Manager, Admin)\n- Edit user profiles\n- Activate/deactivate accounts`,
    keywords: ["users", "accounts", "roles", "access"],
    category: "Admin",
    pageRoute: "/admin/users",
  },
  {
    key: "page.admin.companies",
    scope: "PAGE",
    title: "Company Management",
    shortText: "Manage company profiles and multi-tenancy settings.",
    bodyMd: `## Company Management\n\nConfigure company profiles for multi-tenant operation.\n\n### Features\n- Company profile management\n- Multi-company support\n- Company-specific settings`,
    keywords: ["companies", "organization", "tenant"],
    category: "Admin",
    pageRoute: "/admin/companies",
  },
  {
    key: "page.admin.factories",
    scope: "PAGE",
    title: "Factory Management",
    shortText: "Configure factories, beds, and production capacity.",
    bodyMd: `## Factory Management\n\nSet up and manage production facilities.\n\n### Features\n- Add/edit factories with location and maps\n- Configure production beds\n- Set capacity limits\n- CFMEU calendar integration`,
    keywords: ["factories", "production", "beds", "capacity"],
    category: "Admin",
    pageRoute: "/admin/factories",
  },
  {
    key: "page.admin.customers",
    scope: "PAGE",
    title: "Customer Management",
    shortText: "Manage customer records and contact details.",
    bodyMd: `## Customer Management\n\nMaintain your customer database.\n\n### Features\n- Add and edit customer profiles\n- Track contact information\n- Link customers to jobs`,
    keywords: ["customers", "clients", "contacts"],
    category: "Admin",
    pageRoute: "/admin/customers",
  },
  {
    key: "page.admin.suppliers",
    scope: "PAGE",
    title: "Supplier Management",
    shortText: "Manage supplier records for procurement.",
    bodyMd: `## Supplier Management\n\nMaintain your supplier database for procurement.\n\n### Features\n- Add and edit supplier profiles\n- Track contact and payment details\n- Link suppliers to purchase orders`,
    keywords: ["suppliers", "vendors", "procurement"],
    category: "Admin",
    pageRoute: "/admin/suppliers",
  },
  {
    key: "page.admin.items",
    scope: "PAGE",
    title: "Item Catalog",
    shortText: "Manage the catalog of items available for purchase orders.",
    bodyMd: `## Item Catalog\n\nMaintain the master list of items for procurement.\n\n### Features\n- Add/edit items with categories\n- Set unit of measure\n- Manage item categories\n- Link items to purchase orders`,
    keywords: ["items", "catalog", "products", "inventory"],
    category: "Admin",
    pageRoute: "/admin/items",
  },
  {
    key: "page.admin.devices",
    scope: "PAGE",
    title: "Device Management",
    shortText: "Register and manage mobile devices for the system.",
    bodyMd: `## Device Management\n\nTrack and manage registered mobile devices.\n\n### Features\n- View registered devices\n- Device authentication management\n- Usage tracking`,
    keywords: ["devices", "mobile", "registration"],
    category: "Admin",
    pageRoute: "/admin/devices",
  },
  {
    key: "page.admin.panel-types",
    scope: "PAGE",
    title: "Panel Types",
    shortText: "Configure panel type classifications and attributes.",
    bodyMd: `## Panel Types\n\nDefine and manage panel type categories.\n\n### Features\n- Create panel type definitions\n- Set default attributes\n- Categorize panels for production`,
    keywords: ["panel types", "classification", "categories"],
    category: "Admin",
    pageRoute: "/admin/panel-types",
  },
  {
    key: "page.admin.document-config",
    scope: "PAGE",
    title: "Document Configuration",
    shortText: "Configure document categories, types, and settings.",
    bodyMd: `## Document Configuration\n\nSet up document management categories and rules.\n\n### Features\n- Define document categories\n- Configure naming conventions\n- Set access permissions`,
    keywords: ["documents", "configuration", "categories"],
    category: "Admin",
    pageRoute: "/admin/document-config",
  },
  {
    key: "page.admin.checklist-templates",
    scope: "PAGE",
    title: "Checklist Templates",
    shortText: "Create and manage checklist templates with conditional fields.",
    bodyMd: `## Checklist Templates\n\nDesign checklist templates for quality inspections.\n\n### Features\n- Create custom templates\n- Add conditional field logic\n- Define required fields and photo evidence\n- System-locked templates for standard inspections`,
    keywords: ["checklist", "templates", "quality", "inspection"],
    category: "Admin",
    pageRoute: "/admin/checklist-templates",
  },
  {
    key: "page.admin.user-permissions",
    scope: "PAGE",
    title: "User Permissions",
    shortText: "Configure granular per-user access permissions.",
    bodyMd: `## User Permissions\n\nSet up fine-grained access control for each user.\n\n### Permission Levels\n- **Hidden** - Feature not visible to user\n- **View** - Read-only access\n- **View and Update** - Full access\n\n### Features\n- Per-user permission configuration\n- Function-level access control\n- Bulk permission updates`,
    keywords: ["permissions", "access", "roles", "security"],
    category: "Admin",
    pageRoute: "/admin/user-permissions",
  },
  {
    key: "page.admin.zones",
    scope: "PAGE",
    title: "Zone Management",
    shortText: "Configure zones for organizing work areas.",
    bodyMd: `## Zone Management\n\nDefine and manage work zones for organization.\n\n### Features\n- Create and edit zones\n- Organize work areas`,
    keywords: ["zones", "areas", "organization"],
    category: "Admin",
    pageRoute: "/admin/zones",
  },
  {
    key: "page.admin.asset-register",
    scope: "PAGE",
    title: "Asset Register",
    shortText: "Comprehensive asset management with lifecycle tracking.",
    bodyMd: `## Asset Register\n\nManage company assets from acquisition to disposal.\n\n### Features\n- Register assets with 50+ fields\n- Auto-generated asset tags (AST-YYMM-NNNN)\n- Depreciation tracking\n- Maintenance scheduling\n- Transfer history\n- Insurance and lease management\n- AI-powered asset analysis`,
    keywords: ["assets", "equipment", "inventory", "depreciation"],
    category: "Admin",
    pageRoute: "/admin/asset-register",
  },
  {
    key: "page.admin.help",
    scope: "PAGE",
    title: "Help Management",
    shortText: "Create and manage help articles for the in-app help system.",
    bodyMd: `## Help Management\n\nAdmin interface for managing in-app help content.\n\n### Features\n- Create, edit, and archive help entries\n- Manage page-level and micro-level help content\n- Version history tracking\n- Search and filter entries\n- Markdown content editing\n\n### Help Entry Types\n- **PAGE** - Full page help articles\n- **FIELD** - Field-level tooltip help\n- **ACTION** - Button/action explanations\n- **COLUMN** - Table column descriptions\n- **GENERAL** - General help articles`,
    keywords: ["help", "documentation", "admin", "articles"],
    category: "Admin",
    pageRoute: "/admin/help",
  },
  {
    key: "page.help",
    scope: "PAGE",
    title: "Help Center",
    shortText: "Search and browse help articles to learn about the system.",
    bodyMd: `## Help Center\n\nYour central resource for learning about the system.\n\n### Features\n- **Search** - Find help articles by keyword\n- **Categories** - Browse by topic area\n- **Recently Updated** - See the latest documentation updates\n- **Feedback** - Report unclear or missing documentation`,
    keywords: ["help", "documentation", "search", "support"],
    category: "General",
    pageRoute: "/help",
  },
];

export async function seedHelpEntries() {
  console.log("[Help] Checking for existing help entries...");

  for (const entry of pageHelp) {
    const [existing] = await db
      .select()
      .from(helpEntries)
      .where(eq(helpEntries.key, entry.key));

    if (!existing) {
      await db.insert(helpEntries).values({
        key: entry.key,
        scope: entry.scope,
        title: entry.title,
        shortText: entry.shortText,
        bodyMd: entry.bodyMd,
        keywords: entry.keywords,
        category: entry.category,
        pageRoute: entry.pageRoute || null,
        status: "PUBLISHED",
      });
    }
  }

  const [count] = await db.select({ count: helpEntries.id }).from(helpEntries);
  console.log(`[Help] Help entries seeded. Total entries in database: checked.`);
}
