import multer from "multer";
import { z } from "zod";
import { storage } from "../../storage";

export const panelImportSchema = z.object({
  data: z.array(z.record(z.any())),
  jobId: z.string().optional(),
});

export const estimateImportBodySchema = z.object({
  replace: z.string().optional(),
});

export const ALLOWED_IMPORT_TYPES = [
  "application/vnd.ms-excel",
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  "text/csv",
];

export const upload = multer({ 
  storage: multer.memoryStorage(),
  limits: { fileSize: 25 * 1024 * 1024 },
  fileFilter: (_req, file, cb) => {
    if (ALLOWED_IMPORT_TYPES.includes(file.mimetype)) {
      cb(null, true);
    } else {
      cb(new Error(`File type ${file.mimetype} not allowed. Only Excel and CSV files are accepted.`));
    }
  },
});

export async function buildPanelTypeMap(companyId: string) {
  const panelTypeConfigs = await storage.getAllPanelTypes(companyId);
  if (panelTypeConfigs.length === 0) {
    return null;
  }
  const panelTypesByNameOrCode = new Map<string, string>();
  panelTypeConfigs.forEach(pt => {
    const normalizedName = pt.name.toUpperCase().replace(/ /g, "_");
    const normalizedCode = pt.code.toUpperCase().replace(/ /g, "_");
    panelTypesByNameOrCode.set(normalizedName, pt.code);
    panelTypesByNameOrCode.set(normalizedCode, pt.code);
  });
  const panelTypesList = panelTypeConfigs.map(pt => `${pt.name} (${pt.code})`).join(", ");
  return { panelTypesByNameOrCode, panelTypesList };
}

export const HEADER_MAPPING: Record<string, string> = {
  "column": "panelMark", "column no": "panelMark", "columnno": "panelMark",
  "panelmark": "panelMark", "panel mark": "panelMark", "mark": "panelMark", "element": "panelMark",
  "building": "building", "zone": "zone",
  "structural elevation number": "structuralElevation", "structural elevation no": "structuralElevation",
  "structuralelevation": "structuralElevation", "structuralelevationno": "structuralElevation",
  "level": "level",
  "column type": "panelType", "columntype": "panelType", "paneltype": "panelType", "panel type": "panelType", "type": "panelType",
  "reckli detail": "reckliDetail", "recklidetail": "reckliDetail",
  "thickness": "thickness", "width": "width", "height": "height",
  "gross area m2": "areaM2", "grossaream2": "areaM2",
  "net area m2": "areaM2", "net area": "areaM2", "netaream2": "areaM2", "area": "areaM2",
  "concrete strength mpa": "concreteStrength", "concrete strength": "concreteStrength",
  "concretestrength": "concreteStrength", "concretestrengthmpa": "concreteStrength",
  "vol m3": "volumeM3", "vol": "volumeM3", "volm3": "volumeM3", "volume": "volumeM3",
  "weight t": "weightT", "weight": "weightT", "weightt": "weightT", "mass": "weightT",
  "colum qty": "qty", "columqty": "qty", "qty": "qty", "quantity": "qty",
  "rebates": "rebates", "num rebates": "rebates",
  "fire rate": "fireRate", "firerate": "fireRate", "frl": "fireRate",
  "caulking fire": "caulkingFire", "caulkingfire": "caulkingFire",
  "openings": "openings",
  "net weight": "netWeight", "netweight": "netWeight",
  "gross area": "grossArea", "grossarea": "grossArea",
  "crane capacity weight": "craneCapacityWeight", "cranecapacityweight": "craneCapacityWeight",
  "crane check": "craneCheck", "cranecheck": "craneCheck",
  "grout table manual": "groutTableManual", "grouttablemanual": "groutTableManual",
  "grout to use": "groutToUse", "grouttouse": "groutToUse",
  "grout strength": "groutStrength", "groutstrength": "groutStrength",
  "vertical reo qty": "verticalReoQty", "verticalreoqty": "verticalReoQty",
  "vertical reo type": "verticalReoType", "verticalreotype": "verticalReoType",
  "horizontal reo qty": "horizontalReoQty", "horizontalreoqty": "horizontalReoQty",
  "horizontal reo type": "horizontalReoType", "horizontalreotype": "horizontalReoType",
  "horizontal reo text": "horizontalReoText", "horizontalreotext": "horizontalReoText",
  "horizontal reo at": "horizontalReoAt", "horizontalreoat": "horizontalReoAt",
  "mesh qty": "meshQty", "meshqty": "meshQty",
  "mesh type": "meshType", "meshtype": "meshType",
  "fitments reo qty": "fitmentsReoQty", "fitmentsreoqty": "fitmentsReoQty",
  "fitments reo type": "fitmentsReoType", "fitmentsreotype": "fitmentsReoType",
  "u bars qty": "uBarsQty", "ubarsqty": "uBarsQty", "u bar qty": "uBarsQty",
  "u bars type": "uBarsType", "ubarstype": "uBarsType", "u bar type": "uBarsType",
  "ligs qty": "ligsQty", "ligsqty": "ligsQty",
  "ligs type": "ligsType", "ligstype": "ligsType",
  "blockout bars qty": "blockoutBarsQty", "blockoutbarsqty": "blockoutBarsQty",
  "blockout bars type": "blockoutBarsType", "blockoutbarstype": "blockoutBarsType",
  "additional reo qty 1": "additionalReoQty1", "additionalreoqty1": "additionalReoQty1",
  "additional reo type 1": "additionalReoType1", "additionalreotype1": "additionalReoType1",
  "additional reo qty 2": "additionalReoQty2", "additionalreoqty2": "additionalReoQty2",
  "additional reo type 2": "additionalReoType2", "additionalreotype2": "additionalReoType2",
  "additional reo qty 3": "additionalReoQty3", "additionalreoqty3": "additionalReoQty3",
  "additional reo type 3": "additionalReoType3", "additionalreotype3": "additionalReoType3",
  "additional reo qty 4": "additionalReoQty4", "additionalreoqty4": "additionalReoQty4",
  "additional reo type 4": "additionalReoType4", "additionalreotype4": "additionalReoType4",
  "top fixing qty": "topFixingQty", "topfixingqty": "topFixingQty",
  "top fixing type": "topFixingType", "topfixingtype": "topFixingType",
  "trimmer bars qty": "trimmerBarsQty", "trimmerbarsqty": "trimmerBarsQty",
  "trimmer bars type": "trimmerBarsType", "trimmerbarstype": "trimmerBarsType",
  "ligs reo qty": "ligsReoQty", "ligsreoqty": "ligsReoQty",
  "ligs reo type": "ligsReoType", "ligsreotype": "ligsReoType",
  "additional reo type": "additionalReoType", "additionalreotype": "additionalReoType",
  "additional reo qty": "additionalReoQty", "additionalreoqty": "additionalReoQty",
  "additional reo frl type": "additionalReoFrlType", "additionalreofrltype": "additionalReoFrlType",
  "tie reinforcement": "tieReinforcement", "tiereinforcement": "tieReinforcement",
  "grout tubes bottom qty": "groutTubesBottomQty", "grouttubsbottomqty": "groutTubesBottomQty",
  "grout tubes bottom type": "groutTubesBottomType", "grouttubsbottomtype": "groutTubesBottomType",
  "grout tubes top qty": "groutTubesTopQty", "grouttubstopqty": "groutTubesTopQty",
  "grout tubes top type": "groutTubesTopType", "grouttubstoptype": "groutTubesTopType",
  "ferrules qty": "ferrulesQty", "ferrulesqty": "ferrulesQty",
  "ferrules type": "ferrulesType", "ferrulestype": "ferrulesType",
  "fitments qty 2": "fitmentsQty2", "fitmentsqty2": "fitmentsQty2",
  "fitments type 2": "fitmentsType2", "fitmentstype2": "fitmentsType2",
  "fitments qty 3": "fitmentsQty3", "fitmentsqty3": "fitmentsQty3",
  "fitments type 3": "fitmentsType3", "fitmentstype3": "fitmentsType3",
  "fitments qty 4": "fitmentsQty4", "fitmentsqty4": "fitmentsQty4",
  "fitments type 4": "fitmentsType4", "fitmentstype4": "fitmentsType4",
  "plates qty": "platesQty", "platesqty": "platesQty",
  "plates type": "platesType", "platestype": "platesType",
  "plates qty 2": "platesQty2", "platesqty2": "platesQty2",
  "plates type 2": "platesType2", "platestype2": "platesType2",
  "plates qty 3": "platesQty3", "platesqty3": "platesQty3",
  "plates type 3": "platesType3", "platestype3": "platesType3",
  "plates qty 4": "platesQty4", "platesqty4": "platesQty4",
  "plates type 4": "platesType4", "platestype4": "platesType4",
  "dowel bars length": "dowelBarsLength", "dowelbarslength": "dowelBarsLength",
  "dowel bars qty": "dowelBarsQty", "dowelbarsqty": "dowelBarsQty",
  "dowel bars type": "dowelBarsType", "dowelbarstype": "dowelBarsType",
  "dowel bars length 2": "dowelBarsLength2", "dowelbarslength2": "dowelBarsLength2",
  "dowel bars qty 2": "dowelBarsQty2", "dowelbarsqty2": "dowelBarsQty2",
  "dowel bars type 2": "dowelBarsType2", "dowelbarstype2": "dowelBarsType2",
  "lifter qty a": "lifterQtyA", "lifterqtya": "lifterQtyA",
  "lifters type": "liftersType", "lifterstype": "liftersType",
  "lifter qty b": "lifterQtyB", "lifterqtyb": "lifterQtyB",
  "safety lifters type": "safetyLiftersType", "safetylifterstype": "safetyLiftersType",
  "lifter qty c": "lifterQtyC", "lifterqtyc": "lifterQtyC",
  "face lifters type": "faceLiftersType", "facelifterstype": "faceLiftersType",
  "inserts qty d": "insertsQtyD", "insertsqtyd": "insertsQtyD",
  "insert type d": "insertTypeD", "inserttyped": "insertTypeD",
  "unit check": "unitCheck", "unitcheck": "unitCheck",
  "order": "order",
  "reo r6": "reoR6", "reor6": "reoR6", "r6": "reoR6",
  "reo n10": "reoN10", "reon10": "reoN10", "n10": "reoN10",
  "reo n12": "reoN12", "reon12": "reoN12", "n12": "reoN12",
  "reo n16": "reoN16", "reon16": "reoN16", "n16": "reoN16",
  "reo n20": "reoN20", "reon20": "reoN20", "n20": "reoN20",
  "reo n24": "reoN24", "reon24": "reoN24", "n24": "reoN24",
  "reo n28": "reoN28", "reon28": "reoN28", "n28": "reoN28",
  "reo n32": "reoN32", "reon32": "reoN32", "n32": "reoN32",
  "mesh sl82": "meshSl82", "meshsl82": "meshSl82", "sl82": "meshSl82",
  "mesh sl92": "meshSl92", "meshsl92": "meshSl92", "sl92": "meshSl92",
  "mesh sl102": "meshSl102", "meshsl102": "meshSl102", "sl102": "meshSl102",
  "dowel n20": "dowelN20", "doweln20": "dowelN20",
  "dowel n24": "dowelN24", "doweln24": "dowelN24",
  "dowel n28": "dowelN28", "doweln28": "dowelN28",
  "dowel n32": "dowelN32", "doweln32": "dowelN32",
  "dowel n36": "dowelN36", "doweln36": "dowelN36",
  "reo tons": "reoTons", "reotons": "reoTons",
  "dowels tons": "dowelsTons", "dowelstons": "dowelsTons",
  "total reo": "totalReo", "totalreo": "totalReo",
  "total kg m3": "totalKgM3", "totalkgm3": "totalKgM3",
  "contract": "contract",
  "reo contract": "reoContract", "reocontract": "reoContract",
};

export const PRIORITY_PATTERNS = [
  { patterns: ["column no", "columnno", "panel mark", "panelmark", "element", "mark", "column"], field: "panelMark" },
  { patterns: ["column type", "columntype", "panel type", "paneltype"], field: "panelType" },
  { patterns: ["structural elevation no", "structural elevation number", "structuralelevationno", "structuralelevation"], field: "structuralElevation" },
  { patterns: ["building"], field: "building" },
  { patterns: ["zone"], field: "zone" },
  { patterns: ["level"], field: "level" },
  { patterns: ["type"], field: "panelType" },
  { patterns: ["reckli detail", "recklidetail"], field: "reckliDetail" },
  { patterns: ["thickness"], field: "thickness" },
  { patterns: ["width"], field: "width" },
  { patterns: ["height"], field: "height" },
  { patterns: ["gross area", "net area", "area"], field: "areaM2" },
  { patterns: ["concrete strength", "concretestrength"], field: "concreteStrength" },
  { patterns: ["vol", "volume"], field: "volumeM3" },
  { patterns: ["weight", "mass"], field: "weightT" },
  { patterns: ["colum qty", "columqty", "qty", "quantity"], field: "qty" },
  { patterns: ["rebates", "num rebates"], field: "rebates" },
  { patterns: ["fire rate", "firerate", "frl"], field: "fireRate" },
  { patterns: ["caulking fire", "caulkingfire"], field: "caulkingFire" },
  { patterns: ["openings"], field: "openings" },
  { patterns: ["net weight", "netweight"], field: "netWeight" },
  { patterns: ["panel gross area", "gross area sqm", "grossarea"], field: "grossArea" },
  { patterns: ["crane capacity weight", "cranecapacityweight"], field: "craneCapacityWeight" },
  { patterns: ["crane check", "cranecheck"], field: "craneCheck" },
  { patterns: ["grout table manual", "grouttablemanual"], field: "groutTableManual" },
  { patterns: ["grout to use", "grouttouse"], field: "groutToUse" },
  { patterns: ["grout strength", "groutstrength"], field: "groutStrength" },
  { patterns: ["vertical reo qty", "verticalreoqty"], field: "verticalReoQty" },
  { patterns: ["vertical reo type", "verticalreotype"], field: "verticalReoType" },
  { patterns: ["horizontal reo qty", "horizontalreoqty"], field: "horizontalReoQty" },
  { patterns: ["horizontal reo type", "horizontalreotype"], field: "horizontalReoType" },
  { patterns: ["horizontal reo text", "horizontalreotext"], field: "horizontalReoText" },
  { patterns: ["horizontal reo at", "horizontalreoat"], field: "horizontalReoAt" },
  { patterns: ["mesh qty", "meshqty"], field: "meshQty" },
  { patterns: ["mesh type", "meshtype"], field: "meshType" },
  { patterns: ["fitments reo qty", "fitmentsreoqty"], field: "fitmentsReoQty" },
  { patterns: ["fitments reo type", "fitmentsreotype"], field: "fitmentsReoType" },
  { patterns: ["u bars qty", "ubarsqty", "u bar qty"], field: "uBarsQty" },
  { patterns: ["u bars type", "ubarstype", "u bar type"], field: "uBarsType" },
  { patterns: ["ligs qty", "ligsqty"], field: "ligsQty" },
  { patterns: ["ligs type", "ligstype"], field: "ligsType" },
  { patterns: ["blockout bars qty", "blockoutbarsqty"], field: "blockoutBarsQty" },
  { patterns: ["blockout bars type", "blockoutbarstype"], field: "blockoutBarsType" },
  { patterns: ["top fixing qty", "topfixingqty"], field: "topFixingQty" },
  { patterns: ["top fixing type", "topfixingtype"], field: "topFixingType" },
  { patterns: ["trimmer bars qty", "trimmerbarsqty"], field: "trimmerBarsQty" },
  { patterns: ["trimmer bars type", "trimmerbarstype"], field: "trimmerBarsType" },
  { patterns: ["grout tubes bottom qty", "grouttubsbottomqty"], field: "groutTubesBottomQty" },
  { patterns: ["grout tubes bottom type", "grouttubsbottomtype"], field: "groutTubesBottomType" },
  { patterns: ["grout tubes top qty", "grouttubstopqty"], field: "groutTubesTopQty" },
  { patterns: ["grout tubes top type", "grouttubstoptype"], field: "groutTubesTopType" },
  { patterns: ["ferrules qty", "ferrulesqty"], field: "ferrulesQty" },
  { patterns: ["ferrules type", "ferrulestype"], field: "ferrulesType" },
  { patterns: ["plates qty", "platesqty"], field: "platesQty" },
  { patterns: ["plates type", "platestype"], field: "platesType" },
  { patterns: ["dowel bars length", "dowelbarslength"], field: "dowelBarsLength" },
  { patterns: ["dowel bars qty", "dowelbarsqty"], field: "dowelBarsQty" },
  { patterns: ["dowel bars type", "dowelbarstype"], field: "dowelBarsType" },
  { patterns: ["lifter qty a", "lifterqtya"], field: "lifterQtyA" },
  { patterns: ["lifters type", "lifterstype"], field: "liftersType" },
  { patterns: ["lifter qty b", "lifterqtyb"], field: "lifterQtyB" },
  { patterns: ["safety lifters type", "safetylifterstype"], field: "safetyLiftersType" },
  { patterns: ["lifter qty c", "lifterqtyc"], field: "lifterQtyC" },
  { patterns: ["face lifters type", "facelifterstype"], field: "faceLiftersType" },
  { patterns: ["inserts qty d", "insertsqtyd"], field: "insertsQtyD" },
  { patterns: ["insert type d", "inserttyped"], field: "insertTypeD" },
  { patterns: ["unit check", "unitcheck"], field: "unitCheck" },
  { patterns: ["order"], field: "order" },
  { patterns: ["r6"], field: "reoR6" },
  { patterns: ["n10"], field: "reoN10" },
  { patterns: ["n12"], field: "reoN12" },
  { patterns: ["n16"], field: "reoN16" },
  { patterns: ["n20"], field: "reoN20" },
  { patterns: ["n24"], field: "reoN24" },
  { patterns: ["n28"], field: "reoN28" },
  { patterns: ["n32"], field: "reoN32" },
  { patterns: ["sl82"], field: "meshSl82" },
  { patterns: ["sl92"], field: "meshSl92" },
  { patterns: ["sl102"], field: "meshSl102" },
  { patterns: ["reo tons", "reotons"], field: "reoTons" },
  { patterns: ["dowels tons", "dowelstons"], field: "dowelsTons" },
  { patterns: ["total reo", "totalreo"], field: "totalReo" },
  { patterns: ["total kg m3", "totalkgm3"], field: "totalKgM3" },
  { patterns: ["contract"], field: "contract" },
  { patterns: ["reo contract", "reocontract"], field: "reoContract" },
];
